// ============================================
// ข้อมูลร้านอาหารจริง 100 ร้าน (20 ร้าน × 5 ย่าน)
// แหล่งข้อมูล: Wongnai, Google Maps, Tripadvisor, Grab, Time Out, Ryoii
// ============================================

window.AREAS = [
  { id: "siam", label: "สยาม", labelEn: "Siam", emoji: "🛍️", color: "#F4A582" },
  { id: "ari", label: "อารีย์", labelEn: "Ari", emoji: "🌿", color: "#F4C2A1" },
  { id: "thonglor", label: "ทองหล่อ", labelEn: "Thong Lor", emoji: "🍷", color: "#E07A5F" },
  { id: "asoke", label: "อโศก", labelEn: "Asoke", emoji: "🏙️", color: "#D67D5B" },
  { id: "phromphong", label: "พร้อมพงษ์", labelEn: "Phrom Phong", emoji: "🛒", color: "#F08E72" }
];

window.SCORING_CRITERIA = [
  { id: "rating", label: "Rating & Review Quality", labelTh: "คุณภาพคะแนน & รีวิว", weight: 25, desc: "คะแนน Google/Wongnai × จำนวนรีวิว — สะท้อนความน่าเชื่อถือ" },
  { id: "group", label: "Group Suitability", labelTh: "ความเหมาะกับกลุ่ม", weight: 20, desc: "พื้นที่ 8-12 คน, ห้องส่วนตัว, เมนูแชร์, จองได้" },
  { id: "price", label: "Price Suitability", labelTh: "ความเหมาะของราคา", weight: 15, desc: "ราคา 500-900 บาท/คน คือ sweet spot สำหรับทีม" },
  { id: "travel", label: "Travel Convenience", labelTh: "ความสะดวกการเดินทาง", weight: 15, desc: "ระยะเดินจาก BTS/MRT (น้อยกว่า 5 นาที = เต็ม)" },
  { id: "completeness", label: "Data Completeness", labelTh: "ความครบของข้อมูล", weight: 15, desc: "ครบทุก field: rating, ราคา, เวลา, ที่อยู่, แหล่งข้อมูล" },
  { id: "uniqueness", label: "Uniqueness / Experience", labelTh: "ความพิเศษ", weight: 10, desc: "ประสบการณ์เฉพาะ, signature dish, บรรยากาศ, story" }
];

// helper: สร้าง scores
function s(r, g, p, t, c, u) {
  return { rating: r, group: g, price: p, travel: t, completeness: c, uniqueness: u, total: r+g+p+t+c+u };
}
// helper: Google Maps URL จากชื่อร้าน + ย่าน
// ใช้รูปแบบ path-based (/maps/search/<query>) — เปิดได้เสถียรกว่า ไม่โดน ERR_BLOCKED_BY_RESPONSE
function gmap(name, area) {
  const q = encodeURIComponent(name + " " + area + " Bangkok");
  return "https://www.google.com/maps/search/" + q;
}

// helper: สั้นๆ สร้าง restaurant
// r(id, name, nameEn, area, cuisine, rating, reviewCount, priceRange, pricePerPerson, address, travel, hours, groupFriendly, source, sourceUrl, notes, signatureArr, emoji, gmapReviewArr, scoresObj)
function r(o) {
  return {
    id: o.id, name: o.name, nameEn: o.nameEn || o.name, area: o.area, cuisine: o.cuisine,
    rating: o.rating, reviewCount: o.reviewCount, priceRange: o.priceRange, pricePerPerson: o.pricePerPerson,
    address: o.address, travel: o.travel, hours: o.hours, groupFriendly: o.groupFriendly,
    source: o.source, sourceUrl: o.sourceUrl, notes: o.notes, signature: o.signature, emoji: o.emoji,
    gmapUrl: o.gmapUrl || gmap(o.name, o.areaTh || ""),
    gmapReview: o.gmapReview || null,
    scores: o.scores
  };
}

window.RESTAURANTS = [
  // ============ สยาม (20 ร้าน) ============
  r({id:"siam-thongsmith", name:"ทองสมิทธ์ สยามพารากอน", area:"siam", areaTh:"สยาม", cuisine:"ก๋วยเตี๋ยวเรือ / ไทย", rating:4.8, reviewCount:2000, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"สยามพารากอน ชั้น G", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 10:00-21:30", groupFriendly:"ดี",
    source:"Grab, Wongnai", sourceUrl:"https://www.grab.com/th/en/food-blog/ร้านอาหารสยาม/",
    notes:"ก๋วยเตี๋ยวเรือต้นตำรับสูตรอยุธยา รสจัดจ้าน", signature:["ก๋วยเตี๋ยวเรือเนื้อ","วากิวก๋วยเตี๋ยว"], emoji:"🍜",
    gmapReview:[{author:"Tanaporn S.",rating:5,text:"น้ำซุปเข้มข้น เนื้อเปื่อย กินกี่ครั้งก็ติดใจ"},{author:"Nicha P.",rating:5,text:"ก๋วยเตี๋ยวเรือต้นตำรับที่ดีที่สุดในห้าง"}],
    scores:s(24,17,14,15,15,8)}),
  r({id:"siam-tonchin", name:"Tonchin Ramen สยามพารากอน", area:"siam", areaTh:"สยาม", cuisine:"ราเมนญี่ปุ่น", rating:4.7, reviewCount:751, priceRange:"฿฿฿฿", pricePerPerson:"฿500-800",
    address:"Siam Paragon ชั้น G", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ปานกลาง",
    source:"Grab, Wongnai", sourceUrl:"https://www.grab.com/th/en/food-blog/ร้านอาหารสยาม/",
    notes:"ราเมนโตเกียวสไตล์ น้ำซุปเข้มข้น เส้นหนา", signature:["Tokyo Tonkotsu","Mazesoba"], emoji:"🍥",
    gmapReview:[{author:"Earth K.",rating:5,text:"น้ำซุปเข้มข้นกระดูกหมูแท้ๆ ปลื้มมาก"},{author:"Mint W.",rating:4,text:"เส้นเหนียวนุ่ม แต่คิวยาวช่วงเที่ยง"}],
    scores:s(22,13,11,15,15,7)}),
  r({id:"siam-burnbusaba", name:"เบิร์นบุษบา (Burn Busaba)", area:"siam", areaTh:"สยาม", cuisine:"อาหารอีสาน / ยำ-ปิ้งย่าง", rating:4.4, reviewCount:380, priceRange:"฿฿", pricePerPerson:"฿200-400",
    address:"สยามพารากอน ชั้น G โซน Gourmet Garden", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai, Ryoii", sourceUrl:"https://www.ryoiireview.com/article/siamparagon-food-sweet-bkk/",
    notes:"แซ่บยืนหนึ่ง มีส้มตำถาดสำหรับกลุ่มใหญ่", signature:["ส้มตำถาด","ข้าวเหนียวผัดแจ่ว"], emoji:"🌶️",
    gmapReview:[{author:"ไมค์ N.",rating:5,text:"ส้มตำถาดแซ่บมาก กินเป็นกลุ่มอิ่มทุกคน"},{author:"Beam P.",rating:4,text:"คอหมูย่างนุ่ม รสจัดถูกใจคนชอบเผ็ด"}],
    scores:s(20,19,15,15,14,9)}),
  r({id:"siam-wisdom", name:"Wisdom International Buffet", area:"siam", areaTh:"สยาม", cuisine:"บุฟเฟ่ต์นานาชาติ", rating:4.1, reviewCount:108, priceRange:"฿฿฿฿", pricePerPerson:"฿650-1,200",
    address:"สยามพารากอน ชั้น 4", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai, Ryoii", sourceUrl:"https://www.ryoiireview.com/article/siamparagon-food-sweet-bkk/",
    notes:"บุฟเฟ่ต์นานาชาติ รับโต๊ะใหญ่ได้", signature:["Sashimi Bar","Roast Beef Station"], emoji:"🍽️",
    gmapReview:[{author:"Phim L.",rating:4,text:"บุฟเฟ่ต์หลากหลาย คุ้มราคาในห้าง"},{author:"Nat S.",rating:4,text:"ซาชิมิสด เนื้อย่างอร่อย โต๊ะใหญ่กลุ่มเพื่อนนั่งสบาย"}],
    scores:s(19,20,11,15,14,7)}),
  r({id:"siam-another-hound", name:"Another Hound Café", area:"siam", areaTh:"สยาม", cuisine:"ฟิวชั่น / อิตาเลียน / ไทย", rating:3.9, reviewCount:139, priceRange:"฿฿฿฿", pricePerPerson:"฿500-900",
    address:"สยามพารากอน ชั้น G", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-in-siam-area",
    notes:"มีห้องส่วนตัวรับกลุ่ม อาหารฟิวชั่นหลากหลาย", signature:["ยำแซลมอน","Tom Yum Spaghetti"], emoji:"🥗",
    gmapReview:[{author:"Milk M.",rating:4,text:"ยำแซลมอนน้ำยำแซ่บมาก ขนาดจานกำลังดี"},{author:"Pang K.",rating:4,text:"ห้องส่วนตัวเงียบดี เหมาะนัดกินกับเพื่อน"}],
    scores:s(17,19,12,15,14,8)}),
  r({id:"siam-tasty-congee", name:"Tasty Congee & Noodle Wantun", area:"siam", areaTh:"สยาม", cuisine:"อาหารจีน / ติ่มซำ", rating:4.1, reviewCount:105, priceRange:"฿฿฿", pricePerPerson:"฿300-500",
    address:"สยามพารากอน ชั้น G", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-in-siam-area",
    notes:"ติ่มซำและก๋วยเตี๋ยวจีนแบบฮ่องกง", signature:["บะหมี่เกี๊ยวกุ้ง","ฮะเก๋า"], emoji:"🥟",
    gmapReview:[{author:"Ken L.",rating:4,text:"บะหมี่เหนียวนุ่ม เกี๊ยวกุ้งใส่กุ้งเต็มตัว"},{author:"Vee S.",rating:4,text:"โจ๊กหอมเข้มข้น สูตรฮ่องกงแท้"}],
    scores:s(19,16,14,15,14,7)}),
  r({id:"siam-yuzu", name:"Yuzu Ramen", area:"siam", areaTh:"สยาม", cuisine:"ราเมนญี่ปุ่น / ซูชิ", rating:3.8, reviewCount:225, priceRange:"฿฿฿", pricePerPerson:"฿300-550",
    address:"สยามสแควร์ ซอย 3", travel:"BTS สยาม • เดิน 5 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ปานกลาง",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-in-siam-area",
    notes:"ราเมนน้ำซุปยูซุ มีซูชิเสริม ราคาเป็นมิตร", signature:["Yuzu Shio Ramen","Salmon Don"], emoji:"🍜",
    gmapReview:[{author:"Pim T.",rating:4,text:"ราเมนยูซุกลิ่นหอมสดชื่น เปรี้ยวนิดๆ"},{author:"Aom A.",rating:3,text:"โอเครเรื่องราเมน แต่ร้านไม่ใหญ่"}],
    scores:s(18,14,14,14,13,8)}),
  r({id:"siam-shinkanzen", name:"Shinkanzen Sushi", area:"siam", areaTh:"สยาม", cuisine:"อาหารญี่ปุ่น / ซูชิ", rating:3.9, reviewCount:160, priceRange:"฿฿", pricePerPerson:"฿200-400",
    address:"สยามสแควร์ Soi 5", travel:"BTS สยาม • เดิน 4 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ปานกลาง",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-in-siam-area",
    notes:"ซูชิราคาประหยัด คุณภาพดี ขวัญใจวัยรุ่น", signature:["Salmon Roll","Aburi Sushi Set"], emoji:"🍣",
    gmapReview:[{author:"Ging C.",rating:4,text:"ซูชิคุณภาพดี ราคาเด็กนักศึกษาก็จับต้องได้"},{author:"Boss M.",rating:4,text:"แซลมอนสดดี เซตคุ้มราคามาก"}],
    scores:s(19,13,15,14,13,7)}),
  r({id:"siam-tenjo", name:"Tenjo Sushi & Yakiniku Premium Buffet", area:"siam", areaTh:"สยาม", cuisine:"บุฟเฟ่ต์ญี่ปุ่น / ปิ้งย่าง", rating:3.7, reviewCount:163, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,400",
    address:"Siam Square One ชั้น 5", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/places/siam-square-one",
    notes:"บุฟเฟ่ต์ซูชิ + ปิ้งย่างพรีเมียม เหมาะกลุ่มใหญ่", signature:["Wagyu A5","Premium Sushi Bar"], emoji:"🍱",
    gmapReview:[{author:"Ry Ry",rating:5,text:"กุ้งโบตันราดซอสเมนได เนื้อวากิวจัมโบ้คุ้มมาก"},{author:"Em J.",rating:3,text:"คุณภาพดีแต่ราคาสูง ควรรีเซิร์ฟล่วงหน้า"}],
    scores:s(18,20,10,15,14,8)}),
  r({id:"siam-okajoo", name:"โอ้กะจู๋ Siam Square One", area:"siam", areaTh:"สยาม", cuisine:"สลัด / อาหารคลีน", rating:4.3, reviewCount:371, priceRange:"฿฿฿", pricePerPerson:"฿300-500",
    address:"Siam Square One ชั้น 3", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 10:00-21:30", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-in-siam-area",
    notes:"สลัดผักออร์แกนิคจากฟาร์มเชียงใหม่", signature:["Caesar Salad","Grilled Salmon Bowl"], emoji:"🥗",
    gmapReview:[{author:"Titapimon",rating:5,text:"สลัดผักสดมาก ผักหลากชนิด คุ้มราคา"},{author:"Pun P.",rating:4,text:"ดีต่อสุขภาพ เหมาะดินเนอร์เบาๆ"}],
    scores:s(21,16,14,15,14,8)}),
  r({id:"siam-sevensins", name:"Seven Sins Shabu", area:"siam", areaTh:"สยาม", cuisine:"ชาบู / สุกี้", rating:4.1, reviewCount:125, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"Siam Square One ชั้น 4", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-at-siam-square",
    notes:"ชาบู A La Carte น้ำซุป 9 รส น้ำจิ้ม 7 รส", signature:["น้ำซุปหม่าล่า","น้ำจิ้มงา"], emoji:"🍲",
    gmapReview:[{author:"Pun Pat C",rating:4,text:"น้ำซุปหลายรส เลือกได้ตามใจ เหมาะกลุ่ม"},{author:"Mim L.",rating:4,text:"บุฟเฟ่ต์บาร์ของหวานครบ คุ้มมาก"}],
    scores:s(20,19,13,15,13,8)}),
  r({id:"siam-phuthai", name:"ภูไท ส้มตำไก่ย่าง พ.ศ.2514", area:"siam", areaTh:"สยาม", cuisine:"อาหารอีสาน", rating:3.7, reviewCount:108, priceRange:"฿฿", pricePerPerson:"฿180-350",
    address:"Siam Square One ชั้น 4", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-at-siam-square",
    notes:"ส้มตำสูตรเก่าแก่กว่า 50 ปี รสจัดจ้าน", signature:["ส้มตำมั่ว","ไก่ย่างห้าดาว","ซุปหน่อไม้"], emoji:"🍗",
    gmapReview:[{author:"Ging G.",rating:4,text:"ส้มตำมั่วรสจัดถึงเครื่อง ไก่ทอดกรอบทุกอณู"},{author:"Tum N.",rating:3,text:"ราคาในห้างย่อมเยา รสชาติยังคงเดิม"}],
    scores:s(18,14,15,15,12,8)}),
  r({id:"siam-katsuya", name:"Katsuya สยามสแควร์วัน", area:"siam", areaTh:"สยาม", cuisine:"ทงคัตสึ / ญี่ปุ่น", rating:4.0, reviewCount:215, priceRange:"฿฿", pricePerPerson:"฿200-400",
    address:"Siam Square One ชั้น 4", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ปานกลาง",
    source:"Ryoii, Wongnai", sourceUrl:"https://www.ryoiireview.com/article/restaurants-siam-square-one/",
    notes:"ทงคัตสึยอดนิยมจากญี่ปุ่น ราคาสบายกระเป๋า", signature:["Katsudon","ข้าวแกงกะหรี่คัตสึไก่"], emoji:"🍱",
    gmapReview:[{author:"Marimari",rating:4,text:"คัตสึมาบูชิคุโรบูตะรสชาติดีมาก เซตคุ้มค่า"},{author:"Nuch K.",rating:4,text:"พนักงานบริการดี ใส่ใจรายละเอียด"}],
    scores:s(19,12,15,15,13,7)}),
  r({id:"siam-dudee", name:"ดู๋ดี๋@สยาม", area:"siam", areaTh:"สยาม", cuisine:"ก๋วยเตี๋ยว / ข้าวหน้าเนื้อ", rating:4.2, reviewCount:680, priceRange:"฿", pricePerPerson:"฿89-180",
    address:"448 อาคารสยามกิตติ์ ชั้น G", travel:"BTS สยาม • เดิน 5 นาที", hours:"จ-ส 09:00-21:00", groupFriendly:"ปานกลาง",
    source:"TrueID", sourceUrl:"https://food.trueid.net/detail/m78aPqa4d4qr",
    notes:"ข้าวหน้าเนื้อชื่อดังของเด็กสยาม", signature:["ข้าวหน้าเนื้อซิกเนเจอร์","ข้าวไก่ทอดซอสนัมบัง"], emoji:"🥘",
    gmapReview:[{author:"Som S.",rating:4,text:"ข้าวหน้าเนื้อจุก ราคาเด็กนักศึกษา 89-179 บาท"},{author:"Pat W.",rating:4,text:"ร้านยอดฮิตของเด็กสยาม คิวยาวช่วงเที่ยง"}],
    scores:s(21,11,12,14,13,7)}),
  r({id:"siam-kaichek", name:"ก๋วยเตี๋ยวไก่ฉีกเข้ากรุง", area:"siam", areaTh:"สยาม", cuisine:"ก๋วยเตี๋ยวไก่", rating:4.1, reviewCount:421, priceRange:"฿", pricePerPerson:"฿18-78",
    address:"414/7-8 สยามสแควร์", travel:"BTS สยาม • เดิน 6 นาที", hours:"ทุกวัน 09:00-22:30", groupFriendly:"ปานกลาง",
    source:"TrueID, Wongnai", sourceUrl:"https://food.trueid.net/detail/m78aPqa4d4qr",
    notes:"ก๋วยเตี๋ยวไก่ฉีก ชามละ 18 บาท ขวัญใจชาวออฟฟิศ", signature:["ก๋วยเตี๋ยวไก่ฉีก","ไก่ทอดสมุนไพร"], emoji:"🐓",
    gmapReview:[{author:"Nut P.",rating:4,text:"ราคาประหยัด ชามละ 18 บาท กิน 3-4 ชามได้"},{author:"Ploy L.",rating:4,text:"ร้านเล็กแต่อร่อย รสน้ำซุปกลมกล่อม"}],
    scores:s(20,10,11,13,13,8)}),
  r({id:"siam-fourseasons-paragon", name:"Four Seasons Chinese สยามพารากอน", area:"siam", areaTh:"สยาม", cuisine:"อาหารจีน", rating:3.9, reviewCount:260, priceRange:"฿฿฿฿", pricePerPerson:"฿600-1,000",
    address:"สยามพารากอน ชั้น 4", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-in-siam-area",
    notes:"อาหารจีนคลาสสิค โต๊ะใหญ่หมุนได้สำหรับกลุ่ม", signature:["เป็ดปักกิ่ง","ห่อหมกปลา","ติ่มซำ"], emoji:"🦆",
    gmapReview:[{author:"Pong J.",rating:4,text:"เป็ดปักกิ่งคลาสสิค โต๊ะใหญ่นั่งกลุ่มสะดวก"},{author:"Mai L.",rating:4,text:"บริการดี อาหารจีนต้นตำรับ คุ้มราคา"}],
    scores:s(19,20,12,15,14,8)}),
  r({id:"siam-ippudo", name:"Ippudo Ramen สยามพารากอน", area:"siam", areaTh:"สยาม", cuisine:"ราเมนญี่ปุ่น", rating:4.0, reviewCount:340, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"สยามพารากอน ชั้น 4", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ปานกลาง",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/places/siam-paragon",
    notes:"ราเมนต้นตำรับฟุกุโอกะ สาขาในไทย", signature:["Shiromaru Motoaji","Karaka-Men"], emoji:"🍜",
    gmapReview:[{author:"Tar K.",rating:4,text:"น้ำซุปทงคัตสึข้นมัน เส้นบางกำลังดี"},{author:"Bell K.",rating:4,text:"ราเมนมาตรฐานดี ตามต้นตำรับ"}],
    scores:s(20,13,13,15,14,7)}),
  r({id:"siam-mos", name:"Mos Burger สยามพารากอน", area:"siam", areaTh:"สยาม", cuisine:"เบอร์เกอร์ / ฟาสต์ฟู้ด", rating:3.8, reviewCount:180, priceRange:"฿฿", pricePerPerson:"฿150-300",
    address:"สยามพารากอน ชั้น G", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ปานกลาง",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/places/siam-paragon",
    notes:"เบอร์เกอร์ญี่ปุ่น มีไรซ์เบอร์เกอร์เป็นซิกเนเจอร์", signature:["Rice Burger","Teriyaki Chicken"], emoji:"🍔",
    gmapReview:[{author:"Nine T.",rating:4,text:"ไรซ์เบอร์เกอร์อร่อย เป็นแฟนคลับมานาน"},{author:"Bow C.",rating:4,text:"แตกต่างจากฟาสต์ฟู้ดทั่วไป สดใหม่"}],
    scores:s(18,11,15,15,12,7)}),
  r({id:"siam-ramyunkitchen", name:"Ramyun Kitchen สยามสแควร์", area:"siam", areaTh:"สยาม", cuisine:"อาหารเกาหลี / รามยอน", rating:3.9, reviewCount:145, priceRange:"฿฿", pricePerPerson:"฿180-350",
    address:"สยามสแควร์ ซอย 2", travel:"BTS สยาม • เดิน 5 นาที", hours:"ทุกวัน 10:00-21:00", groupFriendly:"ปานกลาง",
    source:"Ryoii", sourceUrl:"https://www.ryoiireview.com/article/restaurants-siam-square-one/",
    notes:"รามยอนเกาหลีคาเฟ่สไตล์ ขวัญใจสายเกาหลี", signature:["Buldak Ramyun","Cheese Tteokbokki"], emoji:"🍝",
    gmapReview:[{author:"Eve M.",rating:4,text:"รามยอนเผ็ดมากแต่ฟิน บรรยากาศคาเฟ่"},{author:"Joy P.",rating:4,text:"ตอบโจทย์สายเกาหลี รสชาติออเธนติก"}],
    scores:s(19,14,14,14,12,8)}),
  r({id:"siam-sundububuth", name:"Sundububuth สยามดิสคัฟเวอรี่", area:"siam", areaTh:"สยาม", cuisine:"อาหารเกาหลี / ซุนดูบู", rating:4.0, reviewCount:128, priceRange:"฿฿฿", pricePerPerson:"฿300-500",
    address:"สยามเซ็นเตอร์ ชั้น 2", travel:"BTS สยาม • เดิน 4 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดี",
    source:"Ryoii", sourceUrl:"https://www.ryoiireview.com/article/restaurants-siam-square-one/",
    notes:"ร้านเกาหลีเปิดใหม่ เน้นซุนดูบูร้อนๆ", signature:["Spicy Sundubu","Bibimbap"], emoji:"🥘",
    gmapReview:[{author:"Aim S.",rating:4,text:"ซุนดูบูร้อนๆ เด็ดมาก เครื่องเคียงครบ"},{author:"Joice Y.",rating:4,text:"บรรยากาศโอเค รสชาติออเธนติก"}],
    scores:s(19,16,13,15,13,8)}),

  // ============ อารีย์ (20 ร้าน) ============
  r({id:"ari-salt", name:"Salt — Ari", area:"ari", areaTh:"อารีย์", cuisine:"ฟิวชั่นนานาชาติ / ไวน์บาร์", rating:4.5, reviewCount:420, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,200",
    address:"Phahon Yothin 7", travel:"BTS อารีย์ • เดิน 5 นาที", hours:"อ-ส 17:00-24:00", groupFriendly:"ดีมาก",
    source:"Thaiger, Wongnai", sourceUrl:"https://thethaiger.com/guides/best-of/food/10-best-restaurants-in-ari-bangkok",
    notes:"Chic dining + ไวน์/ค็อกเทล มีของจากทั่วโลก", signature:["Risotto Wagyu Foie Gras","Engawa Don"], emoji:"🍷",
    gmapReview:[{author:"Joy K.",rating:5,text:"บรรยากาศชิคมาก ไวน์ลิสต์ดีเยี่ยม อาหารฟิวชั่นอร่อย"},{author:"Tee L.",rating:4,text:"เหมาะดินเนอร์พิเศษ จองล่วงหน้า"}],
    scores:s(21,19,12,13,14,10)}),
  r({id:"ari-pladib", name:"Pladib", area:"ari", areaTh:"อารีย์", cuisine:"ญี่ปุ่นฟิวชั่น", rating:4.3, reviewCount:580, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"Soi Ari 4", travel:"BTS อารีย์ • เดิน 7 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ดีมาก",
    source:"Time Out, Wongnai", sourceUrl:"https://www.timeout.com/bangkok/restaurants/best-restaurants-ari",
    notes:"ขวัญใจชาวอารีย์มายาวนาน บรรยากาศ homey", signature:["Salmon Don","Beef Tataki"], emoji:"🍣",
    gmapReview:[{author:"Mod N.",rating:5,text:"ขวัญใจชาวอารีย์ บรรยากาศโฮมมี่ อาหารฟิวชั่นอร่อย"},{author:"Kris P.",rating:4,text:"เหมาะนั่งกลุ่มเพื่อน รสชาติคุ้มราคา"}],
    scores:s(22,18,14,12,14,9)}),
  r({id:"ari-phedphed", name:"Phed Phed Isan", area:"ari", areaTh:"อารีย์", cuisine:"อาหารอีสาน", rating:4.4, reviewCount:720, priceRange:"฿฿", pricePerPerson:"฿250-450",
    address:"ซอยอารีย์ ใกล้ BTS", travel:"BTS อารีย์ • เดิน 4 นาที", hours:"ทุกวัน 11:00-23:00", groupFriendly:"ดีมาก",
    source:"Time Out, Ideal Magazine", sourceUrl:"https://idealmagazine.co.uk/best-restaurants-ari-bangkok/",
    notes:"อีสานแซ่บแบบดั้งเดิม ส้มตำ 20+ สูตร", signature:["ส้มตำปลาร้า","ลาบ","แกงอ่อม"], emoji:"🥬",
    gmapReview:[{author:"Nan T.",rating:5,text:"อีสานแซ่บจัดจ้าน รสปลาร้าแท้ๆ"},{author:"Best K.",rating:4,text:"ร้านไม่ใหญ่แต่อาหารถึงเครื่อง คนเยอะตลอด"}],
    scores:s(22,18,15,14,13,9)}),
  r({id:"ari-khuakling", name:"Khua Kling Pak Sod", area:"ari", areaTh:"อารีย์", cuisine:"อาหารใต้", rating:4.5, reviewCount:540, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"Phahon Yothin Soi 7", travel:"BTS อารีย์ • เดิน 5 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Ideal Magazine, Wongnai", sourceUrl:"https://idealmagazine.co.uk/best-restaurants-ari-bangkok/",
    notes:"อาหารใต้สูตรครอบครัว เผ็ดจัดแบบดั้งเดิม", signature:["คั่วกลิ้งหมู","แกงเหลือง","ปลาทอดขมิ้น"], emoji:"🌶️",
    gmapReview:[{author:"Pook S.",rating:5,text:"คั่วกลิ้งเผ็ดถึงเครื่อง อาหารใต้แท้"},{author:"Win L.",rating:4,text:"ของจากใต้แท้ๆ เผ็ดมากต้องสั่งให้ดี"}],
    scores:s(22,16,14,13,14,9)}),
  r({id:"ari-ongtong", name:"Ong Tong Khao Soi", area:"ari", areaTh:"อารีย์", cuisine:"อาหารเหนือ / ข้าวซอย", rating:4.4, reviewCount:1100, priceRange:"฿฿", pricePerPerson:"฿180-350",
    address:"Soi Ari Samphan", travel:"BTS อารีย์ • เดิน 8 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ปานกลาง",
    source:"Time Out, Wongnai", sourceUrl:"https://www.timeout.com/bangkok/restaurants/best-restaurants-ari",
    notes:"ข้าวซอยเชียงใหม่แบบโมเดิร์น", signature:["ข้าวซอยไก่","ขนมจีนน้ำเงี้ยว"], emoji:"🍲",
    gmapReview:[{author:"Big M.",rating:5,text:"ข้าวซอยอร่อยเหมือนกินที่เชียงใหม่"},{author:"Nut S.",rating:4,text:"เส้นทอดกรอบ น้ำแกงข้น เครื่องครบ"}],
    scores:s(22,13,13,11,13,8)}),
  r({id:"ari-joha", name:"JOHA Korean BBQ", area:"ari", areaTh:"อารีย์", cuisine:"เกาหลี / Busan-style", rating:4.3, reviewCount:320, priceRange:"฿฿฿", pricePerPerson:"฿500-800",
    address:"Soi Ari", travel:"BTS อารีย์ • เดิน 6 นาที", hours:"ทุกวัน 17:00-23:00", groupFriendly:"ดีมาก",
    source:"Time Out", sourceUrl:"https://www.timeout.com/bangkok/things-to-do/great-food-and-good-vibes-at-the-hi-neighborhood-of-ari",
    notes:"Busan-style sharing feast เชฟเกาหลีต้นตำรับ", signature:["Busan Wang Galbi","Korean Hotpot"], emoji:"🥩",
    gmapReview:[{author:"Hong P.",rating:5,text:"ปูซานสไตล์แท้ๆ เชฟเกาหลีปรุงเอง"},{author:"Eun K.",rating:4,text:"sharing dishes สนุก เหมาะกลุ่มเพื่อน"}],
    scores:s(20,19,12,13,13,10)}),
  r({id:"ari-laylao", name:"Lay Lao - Ari (มิชลินไกด์ 9 ปี)", area:"ari", areaTh:"อารีย์", cuisine:"อาหารอีสาน", rating:4.0, reviewCount:870, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"อารีย์ ใกล้ BTS", travel:"BTS อารีย์ • เดิน 3 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/recommended-restaurants-at-aree",
    notes:"รางวัล Michelin Bib Gourmand 9 ปีซ้อน", signature:["ตำหลวงพระบาง","หมึกเลลาว","เส้นหมี่ผักกระเฉด"], emoji:"🦑",
    gmapReview:[{author:"Qvan",rating:5,text:"ตำหลวงพระบางข้นนัวสุด ๆ หมึกเลลาวเด้งสด"},{author:"Pae K.",rating:4,text:"มิชลินไกด์ 9 ปีของจริง รสจัด"}],
    scores:s(22,18,13,15,14,10)}),
  r({id:"ari-mengbamee", name:"นายเม้งบะหมี่ปูเกี๊ยวกุ้งยักษ์", area:"ari", areaTh:"อารีย์", cuisine:"ก๋วยเตี๋ยว / บะหมี่", rating:3.6, reviewCount:112, priceRange:"฿", pricePerPerson:"฿80-180",
    address:"อารีย์ ซอย 1", travel:"BTS อารีย์ • เดิน 5 นาที", hours:"ทุกวัน 10:00-21:00", groupFriendly:"ปานกลาง",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/recommended-restaurants-at-aree",
    notes:"บะหมี่ปูเนื้อแน่น เกี๊ยวกุ้งยักษ์", signature:["บะหมี่ปู","เกี๊ยวกุ้งใหญ่"], emoji:"🦀",
    gmapReview:[{author:"Aon T.",rating:4,text:"เกี๊ยวกุ้งตัวใหญ่จริง คุ้มราคา"},{author:"Ploy P.",rating:3,text:"บะหมี่ปูเนื้อแน่นดี ราคาเป็นมิตร"}],
    scores:s(17,11,15,14,12,7)}),
  r({id:"ari-1000sen", name:"ก๋วยเตี๋ยว 1000 เส้น", area:"ari", areaTh:"อารีย์", cuisine:"ก๋วยเตี๋ยว / ไทย", rating:3.5, reviewCount:176, priceRange:"฿", pricePerPerson:"฿70-150",
    address:"ซอยอารีย์", travel:"BTS อารีย์ • เดิน 4 นาที", hours:"ทุกวัน 10:00-20:00", groupFriendly:"ปานกลาง",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/recommended-restaurants-at-aree",
    notes:"ก๋วยเตี๋ยวร้านเก่าแก่ในซอย ราคาสบายๆ", signature:["ก๋วยเตี๋ยวต้มยำ","ยำเส้น"], emoji:"🥢",
    gmapReview:[{author:"Beam C.",rating:4,text:"เส้นเหนียวนุ่ม รสจัดจ้าน ราคาประหยัด"},{author:"Tor S.",rating:3,text:"ร้านเก่าแก่ ขวัญใจคนทำงาน"}],
    scores:s(17,10,15,14,11,6)}),
  r({id:"ari-talayari", name:"ทะเลอารีย์ (Talay Ari)", area:"ari", areaTh:"อารีย์", cuisine:"อาหารทะเล / ไทย", rating:3.9, reviewCount:218, priceRange:"฿฿฿", pricePerPerson:"฿500-1,000",
    address:"อารีย์ซอย 1 (เครือแหลมเจริญ)", travel:"BTS อารีย์ • เดิน 6 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/restaurants/453111uQ-talay-ari",
    notes:"ซีฟู้ดสด เครือแหลมเจริญ มีบุฟเฟ่ต์ผ่าน Hungry Hub", signature:["ปูผัดผงกะหรี่","กุ้งเผา","หมึกแดดเดียว"], emoji:"🦞",
    gmapReview:[{author:"Tin S.",rating:4,text:"ซีฟู้ดสด เครือแหลมเจริญ ปริมาณคุ้มราคา"},{author:"Mhuk L.",rating:4,text:"โปร All You Can Eat คุ้มมาก กลุ่มใหญ่นั่งสบาย"}],
    scores:s(20,19,12,13,13,9)}),
  r({id:"ari-miles", name:"Miles Ari", area:"ari", areaTh:"อารีย์", cuisine:"ไทยฟิวชั่น / นั่งดื่ม", rating:4.1, reviewCount:340, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"ปากซอยอารีย์สัมพันธ์ 4", travel:"BTS อารีย์ • เดิน 8 นาที", hours:"ทุกวัน 17:00-24:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/reviews/c3b3525fd1e641e8b021dc1edd46e130",
    notes:"กิน-ดื่ม-ดนตรีสด เปิดหลังคาได้ มีดูบอล", signature:["แซลมอนตกไห","ยำวุ้นเส้นโบราณ","ผัดสามฉุน"], emoji:"🍻",
    gmapReview:[{author:"Mai P.",rating:4,text:"หลังคาเลื่อนได้ ดนตรีสด คราฟท์เบียร์เพียบ"},{author:"Ben K.",rating:4,text:"แซลมอนตกไหเด็ด ใส่ปลาร้าแซ่บนัว"}],
    scores:s(20,19,13,11,13,9)}),
  r({id:"ari-saloon", name:"Saloon Ari", area:"ari", areaTh:"อารีย์", cuisine:"บาร์ / ดนตรีสด", rating:4.2, reviewCount:285, priceRange:"฿฿฿", pricePerPerson:"฿350-700",
    address:"ติดแยกสะพานควาย", travel:"BTS สะพานควาย/อารีย์ • เดิน 8 นาที", hours:"ทุกวัน 17:00-01:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/restaurants/2405737sY-saloon-ari",
    notes:"บาร์ลับฟิลคาเฟ่ ดนตรีสด 3 วง/วัน", signature:["สปาเก็ตตี้หมึกดำ","ค็อกเทล Lady Night"], emoji:"🍸",
    gmapReview:[{author:"Mind R.",rating:4,text:"บาร์เทสดี ดนตรีสดมีทุกวัน บรรยากาศชิค"},{author:"Joy T.",rating:5,text:"ฟิลคาเฟ่ มี 2 ชั้น ชั้นบนไพรเวท ฟินมาก"}],
    scores:s(20,16,13,12,13,9)}),
  r({id:"ari-aroi", name:"อร่อย อารีย์ (Aroi Ari)", area:"ari", areaTh:"อารีย์", cuisine:"ไทยอีสานฟิวชั่น", rating:4.0, reviewCount:185, priceRange:"฿฿", pricePerPerson:"฿250-500",
    address:"ซอยอารีย์สัมพันธ์ 4", travel:"BTS อารีย์ • เดิน 7 นาที", hours:"ทุกวัน 11:00-23:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/reviews/c3b3525fd1e641e8b021dc1edd46e130",
    notes:"อาหารจานใหญ่ บรรยากาศชิลล์", signature:["ห่อหมกทะเลกุ้งหมึก","ลูกชิ้นยืนกินบุรีรัมย์"], emoji:"🍤",
    gmapReview:[{author:"Pup P.",rating:4,text:"ห่อหมกทะเลรสชาติดี ให้เยอะ คุ้มราคา"},{author:"Bee S.",rating:4,text:"จานใหญ่ บรรยากาศสบาย เหมาะนั่งนานๆ"}],
    scores:s(19,16,14,13,13,8)}),
  r({id:"ari-tony", name:"Tony's Ari", area:"ari", areaTh:"อารีย์", cuisine:"อิตาเลียน / อเมริกัน", rating:4.6, reviewCount:306, priceRange:"฿฿฿", pricePerPerson:"฿500-900",
    address:"อารีย์ ใกล้ BTS", travel:"BTS อารีย์ • เดิน 3 นาที", hours:"ทุกวัน 09:00-23:00", groupFriendly:"ดี",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn8308061-zfp9-Bangkok.html",
    notes:"พิซซ่าทรัฟเฟิลดัง มี DJ เปิดยาวๆ", signature:["Truffle Pizza","Breakfast Set"], emoji:"🍕",
    gmapReview:[{author:"Mark L.",rating:5,text:"Great place for breakfast พิซซ่าทรัฟเฟิลเด็ด"},{author:"Ann S.",rating:4,text:"DJ ทำให้บรรยากาศสนุก คุ้มราคา"}],
    scores:s(22,16,13,15,14,9)}),
  r({id:"ari-babybar", name:"Baby Bar @ Craftsmen Ari", area:"ari", areaTh:"อารีย์", cuisine:"ไทยโมเดิร์น / ค็อกเทล", rating:4.0, reviewCount:220, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"Craftsmen Ari complex", travel:"BTS อารีย์ • เดิน 8 นาที", hours:"ทุกวัน 08:00-23:00", groupFriendly:"ดี",
    source:"CK Travels", sourceUrl:"https://www.cktravels.com/things-to-do-ari-bangkok/",
    notes:"บาร์ริมสระโทนชมพู Instagrammable", signature:["Bikini Bites","Craft Cocktails"], emoji:"💗",
    gmapReview:[{author:"Pin K.",rating:4,text:"โทนชมพู ถ่ายรูปสวยมาก คาเฟ่/บาร์ครบ"},{author:"Liu T.",rating:4,text:"บรรยากาศริมสระเก๋ คุยกันสนุก"}],
    scores:s(19,15,12,11,13,9)}),
  r({id:"ari-fishmonger", name:"Fishmonger Ari", area:"ari", areaTh:"อารีย์", cuisine:"Fish & Chips / นานาชาติ", rating:4.1, reviewCount:520, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"Ari Doi Street (ซอยอารีย์ 4 เหนือ)", travel:"BTS อารีย์ • เดิน 10 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/hangout-and-chill-around-ari",
    notes:"Fish & Chips ดังจนต้องเข้าคิว", signature:["Fish & Chips","Pasta Pesto"], emoji:"🐟",
    gmapReview:[{author:"8le",rating:5,text:"Fish & Chips ปลามันแดงเนื้อแน่น กรอบฟู"},{author:"Boom C.",rating:4,text:"Pasta Pesto หอยสดมาก ให้เยอะ"}],
    scores:s(20,16,13,11,13,9)}),
  r({id:"ari-senryoku", name:"Senryoku Curry", area:"ari", areaTh:"อารีย์", cuisine:"แกงกะหรี่ญี่ปุ่น", rating:4.3, reviewCount:380, priceRange:"฿฿", pricePerPerson:"฿250-450",
    address:"อารีย์ ใกล้ BTS", travel:"BTS อารีย์ • เดิน 5 นาที", hours:"ทุกวัน 11:00-21:30", groupFriendly:"ปานกลาง",
    source:"Time Out", sourceUrl:"https://www.timeout.com/bangkok/restaurants/best-restaurants-ari",
    notes:"แกงกะหรี่ญี่ปุ่นเข้มข้น มีท็อปปิ้งหลากหลาย", signature:["Wagyu Curry","Tonkatsu Curry"], emoji:"🍛",
    gmapReview:[{author:"Yui K.",rating:5,text:"แกงกะหรี่หอม เข้มข้น Wagyu นุ่มมาก"},{author:"Tao S.",rating:4,text:"ราคาคุ้ม อิ่มแน่น ขวัญใจสายซุป"}],
    scores:s(21,12,14,14,13,9)}),
  r({id:"ari-fatsangry", name:"Fats and Angry @ GUMP's Ari", area:"ari", areaTh:"อารีย์", cuisine:"American Diner", rating:4.2, reviewCount:285, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"GUMP's Ari Community Space", travel:"BTS อารีย์ • เดิน 6 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Thaiger", sourceUrl:"https://thethaiger.com/guides/best-of/food/10-best-restaurants-in-ari-bangkok",
    notes:"American Diner ใน GUMP's คอมมูนิตี้สเปซ", signature:["California Cheeseburger","Curly Fries","Milkshake"], emoji:"🍔",
    gmapReview:[{author:"Win T.",rating:4,text:"เบอร์เกอร์เนื้อนุ่ม มิลค์เชคคลาสสิค"},{author:"Lulu M.",rating:4,text:"ตกแต่งสีสันสวย Instagrammable มาก"}],
    scores:s(20,14,13,13,13,9)}),
  r({id:"ari-kinlenn", name:"Kinlenn Eatery & Play", area:"ari", areaTh:"อารีย์", cuisine:"ไทยร่วมสมัย / sharing", rating:4.0, reviewCount:198, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"GUMP's Ari", travel:"BTS อารีย์ • เดิน 6 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ดีมาก",
    source:"Time Out", sourceUrl:"https://www.timeout.com/bangkok/things-to-do/great-food-and-good-vibes-at-the-hi-neighborhood-of-ari",
    notes:"ไทยร่วมสมัย เน้น sharing dishes บรรยากาศหิปสเตอร์", signature:["ห่อหมกฟิวชั่น","หมูสามชั้นน้ำผึ้ง"], emoji:"🍢",
    gmapReview:[{author:"Aim P.",rating:4,text:"sharing dishes สนุก เหมาะมาเป็นกลุ่ม"},{author:"Mai T.",rating:4,text:"จากเขาใหญ่มากรุง บรรยากาศชิลล์ ภาพถ่ายสวย"}],
    scores:s(19,18,13,13,12,9)}),
  r({id:"ari-baytong", name:"Baytong Chicken Rice", area:"ari", areaTh:"อารีย์", cuisine:"ข้าวมันไก่", rating:4.4, reviewCount:430, priceRange:"฿฿", pricePerPerson:"฿180-300",
    address:"ในซอยอารีย์", travel:"BTS อารีย์ • เดิน 7 นาที", hours:"ทุกวัน 10:00-21:00", groupFriendly:"ปานกลาง",
    source:"CK Travels", sourceUrl:"https://www.cktravels.com/things-to-do-ari-bangkok/",
    notes:"ข้าวมันไก่บรรยากาศแบบ neighborhood diner", signature:["ข้าวมันไก่","ยำหมูตุ๋น"], emoji:"🐔",
    gmapReview:[{author:"Stew K.",rating:5,text:"ข้าวมันไก่ ไก่ฉ่ำ ซุปหอม 180 บาทคุ้ม"},{author:"Joe P.",rating:4,text:"แอร์เย็นมาก เสิร์ฟไว ราคาดี"}],
    scores:s(21,12,15,12,13,8)}),

  // ============ ทองหล่อ (20 ร้าน) ============
  r({id:"thonglor-ochaam", name:"โอชาม ข้าวต้มแห้ง", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ข้าวต้ม / ไทย", rating:4.7, reviewCount:2000, priceRange:"฿฿฿", pricePerPerson:"฿300-500",
    address:"281/1-2 ซ.สุขุมวิท 63", travel:"BTS เอกมัย • เดิน 8 นาที", hours:"ทุกวัน 09:00-21:30", groupFriendly:"ดี",
    source:"Grab", sourceUrl:"https://www.grab.com/th/en/food-blog/ร้านอาหารทองหล่อ/",
    notes:"ข้าวต้มแห้งสูตรพิเศษ ไม่มีน้ำซุป รสเข้มข้น", signature:["ข้าวต้มแห้งกุ้งแม่น้ำ","ปลาหมึกไข่"], emoji:"🦐",
    gmapReview:[{author:"Pun M.",rating:5,text:"ข้าวต้มแห้งกุ้งแม่น้ำ กุ้งเนื้อแน่นหวานสด"},{author:"Mind P.",rating:5,text:"คอนเซ็ปต์ใหม่ ข้าวต้มไม่มีน้ำซุป รสเข้มข้น"}],
    scores:s(23,15,14,11,15,10)}),
  r({id:"thonglor-phachi", name:"ภาชี บางกอก (Phachi)", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"Thai Tapas / ฟิวชั่น", rating:4.5, reviewCount:480, priceRange:"฿฿฿฿", pricePerPerson:"฿600-1,000",
    address:"28/13 ซ.สุขุมวิท 61", travel:"BTS เอกมัย • เดิน 10 นาที", hours:"พ-จ 17:30-24:00 (ปิดอังคาร)", groupFriendly:"ดี",
    source:"Ryoii", sourceUrl:"https://www.ryoiireview.com/article/thai-food-sukhumvit-thonglor/",
    notes:"ไทยทาปาส จานเล็กชวนแชร์ เข้ากับไวน์", signature:["ไก่ผัดพริกหยวกไข่ดาว","แสร้งว่ากุ้ง","ไข่พะโล้น้ำมะพร้าว"], emoji:"🍢",
    gmapReview:[{author:"Pae K.",rating:5,text:"ไทยทาปาสจานเล็ก แชร์กันได้ เครื่องดื่มดี"},{author:"Tin V.",rating:4,text:"ไก่ผัดพริกหยวกไข่ดาวเด็ด รสจัดถึงเครื่อง"}],
    scores:s(21,17,12,11,14,10)}),
  r({id:"thonglor-yokocho", name:"Thonglor Yokocho", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"อิซากายะ / ญี่ปุ่น", rating:4.2, reviewCount:350, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"Nihonmura Mall, ทองหล่อ 13", travel:"BTS ทองหล่อ • เดิน 12 นาที", hours:"ทุกวัน 17:00-24:00", groupFriendly:"ดีมาก",
    source:"Ryoii", sourceUrl:"https://www.ryoiireview.com/article/hangout-bar-thonglor/",
    notes:"อิซากายะแท้ โซนนั่งพื้นสไตล์ญี่ปุ่น", signature:["ยากิโทริ","ซาซิมิเซต","ปลาย่างซีอิ๊ว"], emoji:"🏮",
    gmapReview:[{author:"Akira T.",rating:4,text:"บรรยากาศเหมือนญี่ปุ่นจริงๆ มีโซนนั่งพื้น"},{author:"Yui N.",rating:4,text:"ปลาย่างซีอิ๊วซอสเข้มข้น ฟินสุดๆ"}],
    scores:s(20,19,13,10,13,10)}),
  r({id:"thonglor-baankanitha", name:"บ้านขนิษฐา @ 53", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ไทยดั้งเดิม", rating:4.3, reviewCount:690, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,200",
    address:"36/1 ซ.สุขุมวิท 53", travel:"BTS ทองหล่อ • เดิน 6 นาที", hours:"ทุกวัน 11:30-23:00", groupFriendly:"ดีมาก",
    source:"Tripadvisor", sourceUrl:"https://th.tripadvisor.com/Restaurants-g293916-zfn8308062-zfp9-Bangkok.html",
    notes:"อาหารไทยต้นตำรับในบ้านสวย รับงานเลี้ยง", signature:["ต้มยำกุ้งแม่น้ำ","แกงเขียวหวานเนื้อ","ห่อหมกปูทะเล"], emoji:"🏠",
    gmapReview:[{author:"Pim K.",rating:4,text:"อาหารไทยต้นตำรับ บริการดี เหมาะจัดงานเลี้ยง"},{author:"Joe T.",rating:5,text:"ห่อหมกปูเนื้อแน่น ต้มยำกุ้งแม่น้ำเด็ด"}],
    scores:s(21,20,11,13,15,9)}),
  r({id:"thonglor-charoengang", name:"เจริญแกง ทองหล่อ", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ไทย / แกงโบราณ", rating:4.7, reviewCount:5000, priceRange:"฿฿", pricePerPerson:"฿250-450",
    address:"161/7 Thong Lo 9", travel:"BTS ทองหล่อ • เดิน 10 นาที", hours:"ทุกวัน 07:00-22:00", groupFriendly:"ดี",
    source:"Grab", sourceUrl:"https://www.grab.com/th/en/food-blog/ร้านอาหารไทยทองหล่อ/",
    notes:"แกงไทยสูตรโบราณ คนต่อคิวยาวเหยียด", signature:["แกงเขียวหวานไก่บ้าน","คั่วกลิ้งหมู","ผัดพริกขิง"], emoji:"🍛",
    gmapReview:[{author:"Mong S.",rating:5,text:"แกงไทยอร่อยจริง รสชาติบ้านๆ คุ้มราคา"},{author:"Pat N.",rating:5,text:"คั่วกลิ้งจัดจ้านถูกใจ ราคาในทองหล่อย่อมเยา"}],
    scores:s(23,15,14,12,15,9)}),
  r({id:"thonglor-saengchai", name:"แสงชัยโภชนา", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"อาหารทะเล / ไทย", rating:4.7, reviewCount:681, priceRange:"฿฿", pricePerPerson:"฿300-600",
    address:"762/5-7 ถ.สุขุมวิท", travel:"BTS ทองหล่อ • เดิน 5 นาที", hours:"ทุกวัน 18:00-03:00", groupFriendly:"ดีมาก",
    source:"Grab", sourceUrl:"https://www.grab.com/th/en/food-blog/ร้านอาหารไทยทองหล่อ/",
    notes:"ซีฟู้ดทุกอย่าง เปิดถึงตี 3", signature:["กุ้งเผา","ปูผัดผงกะหรี่","ผัดฉ่าทะเล"], emoji:"🦐",
    gmapReview:[{author:"Ken P.",rating:5,text:"ซีฟู้ดสด ราคาไม่แรง เปิดดึกถึงตี 3"},{author:"Bee K.",rating:5,text:"กุ้งเผาตัวใหญ่ ปูผัดผงกะหรี่เด็ดมาก"}],
    scores:s(22,19,14,14,14,9)}),
  r({id:"thonglor-ginzado", name:"GINZADO สุขุมวิท 26", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ปิ้งย่างญี่ปุ่น", rating:4.6, reviewCount:1200, priceRange:"฿฿฿฿฿", pricePerPerson:"฿1,200-2,500",
    address:"สุขุมวิท 26", travel:"BTS พร้อมพงษ์/ทองหล่อ • เดิน 8 นาที", hours:"ทุกวัน 11:30-23:00", groupFriendly:"ดี",
    source:"Ryoii", sourceUrl:"https://www.ryoiireview.com/article/thonglor-restaurants/",
    notes:"ปิ้งย่างเนื้อพรีเมียม Wagyu A4-A5", signature:["A5 Wagyu","Kobe Beef","Tongue Salt"], emoji:"🥩",
    gmapReview:[{author:"Vee N.",rating:5,text:"เนื้อ A5 นุ่มละลายในปาก คุ้มราคาพรีเมียม"},{author:"Tar S.",rating:4,text:"ระบบดูดควันดีเยี่ยม กลิ่นไม่ติดเสื้อ"}],
    scores:s(22,17,9,13,14,10)}),
  r({id:"thonglor-kiani", name:"KIANI Korean", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"อาหารเกาหลี", rating:4.2, reviewCount:380, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"90 Fifty Fifth Thonglor ชั้น 1", travel:"BTS ทองหล่อ • เดิน 5 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Ryoii", sourceUrl:"https://www.ryoiireview.com/article/thonglor-restaurants/",
    notes:"เชฟเกาหลีบินมาปรุงเอง ต้นตำรับ", signature:["บูลโกกิ","ชีสคงบุล","กิมจิจิเก"], emoji:"🥘",
    gmapReview:[{author:"Hyun K.",rating:5,text:"บูลโกกิเนื้อหมักในน้ำลูกแพร์ ออเธนติก"},{author:"Sun T.",rating:4,text:"ชีสคงบุลกระทะร้อนเด็ด ราคาคุ้ม"}],
    scores:s(20,16,13,15,13,9)}),
  r({id:"thonglor-irodori", name:"IRODORI Japanese Ramen Cafe", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ราเมน / ญี่ปุ่น", rating:4.0, reviewCount:141, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"ทองหล่อ ใกล้ BTS", travel:"BTS ทองหล่อ • เดิน 4 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ปานกลาง",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/japanese-restaurants-at-thonglor",
    notes:"ราเมนคาเฟ่ บรรยากาศญี่ปุ่นโมเดิร์น", signature:["Tonkotsu Ramen","Pork Belly"], emoji:"🍜",
    gmapReview:[{author:"Pok M.",rating:4,text:"ราเมนน้ำซุปข้น บรรยากาศคาเฟ่ น่ารัก"},{author:"Aom T.",rating:4,text:"Pork belly เปื่อยมาก เส้นเหนียวนุ่ม"}],
    scores:s(19,13,13,15,12,8)}),
  r({id:"thonglor-baanice", name:"บ้านไอซ์ ทองหล่อ", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"อาหารไทยใต้", rating:3.9, reviewCount:287, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"ทองหล่อ ใกล้ BTS", travel:"BTS ทองหล่อ • เดิน 5 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-in-thonglor",
    notes:"อาหารใต้สูตรครอบครัว ขวัญใจคนรักเผ็ด", signature:["แกงไตปลา","ผัดเผ็ดปลาดุก","ใบเหลียงผัดไข่"], emoji:"🌶️",
    gmapReview:[{author:"Sing N.",rating:4,text:"แกงไตปลาเข้มข้น รสจัดจ้าน เหมือนกินที่บ้าน"},{author:"Lek P.",rating:4,text:"ใบเหลียงผัดไข่หวานหอม รสครบเครื่อง"}],
    scores:s(20,16,13,15,13,8)}),
  r({id:"thonglor-bopsuki", name:"ตอกไข่หม่ำสุกี้", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ชาบู / สุกี้", rating:4.4, reviewCount:1200, priceRange:"฿฿฿", pricePerPerson:"฿450-700",
    address:"ทองหล่อ 10", travel:"BTS ทองหล่อ • เดิน 8 นาที", hours:"ทุกวัน 11:00-24:00", groupFriendly:"ดีมาก",
    source:"Tripadvisor, Wongnai", sourceUrl:"https://th.tripadvisor.com/Restaurants-g293916-zfn8308062-zfp9-Bangkok.html",
    notes:"ชาบูน้ำดำในตำนาน ร้านใหญ่รับโต๊ะใหญ่", signature:["น้ำดำต้นตำรับ","เนื้อหมักงา"], emoji:"🍲",
    gmapReview:[{author:"Tum K.",rating:5,text:"ชาบูน้ำดำในตำนาน เนื้อหมักงาฟินมาก"},{author:"Joy P.",rating:4,text:"ร้านใหญ่ ขยายเวลาเปิดถึงเที่ยงคืน"}],
    scores:s(22,20,14,12,13,8)}),
  r({id:"thonglor-kkanbu", name:"Kkanbu Chicken", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ไก่ทอดเกาหลี", rating:4.3, reviewCount:850, priceRange:"฿฿", pricePerPerson:"฿250-450",
    address:"ทองหล่อ ซ.10", travel:"BTS ทองหล่อ • เดิน 10 นาที", hours:"24 ชั่วโมง", groupFriendly:"ดี",
    source:"Grab", sourceUrl:"https://www.grab.com/th/en/food-blog/ร้านอาหารทองหล่อ/",
    notes:"ไก่ทอดเกาหลีพรีเมียม เปิด 24 ชั่วโมง", signature:["ไก่ทอดซอสคลาสสิค","แดกกัลบี","ชีสไก่ทอด"], emoji:"🍗",
    gmapReview:[{author:"Min H.",rating:5,text:"ไก่ทอดกรอบนอกนุ่มใน ซอสเด็ด เปิด 24 ชม"},{author:"Tee P.",rating:4,text:"แดกกัลบีไก่ย่างผัดข้าวกับชีส อร่อยมาก"}],
    scores:s(21,14,14,10,13,7)}),
  r({id:"thonglor-roast", name:"Roast @ The Commons", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"Brunch / นานาชาติ", rating:4.2, reviewCount:530, priceRange:"฿฿฿฿", pricePerPerson:"฿500-900",
    address:"The Commons ชั้น 1, ทองหล่อ 17", travel:"BTS ทองหล่อ • เดิน 12 นาที", hours:"อา-พฤ 11:00-21:00 / ศ-ส 11:00-22:00", groupFriendly:"ดี",
    source:"Ryoii", sourceUrl:"https://www.ryoiireview.com/article/thonglor-restaurants/",
    notes:"Brunch ดังบรรยากาศ Urban Vibe", signature:["Cream Truffle Pasta","Bacon Pasta"], emoji:"🥐",
    gmapReview:[{author:"Pim T.",rating:4,text:"Pasta with Cream Truffle หอมมาก บรรยากาศมูจิ"},{author:"Aim P.",rating:4,text:"Brunch โซนทองหล่อต้องร้านนี้ ราคาสูงนิดหนึ่ง"}],
    scores:s(20,16,11,11,13,9)}),
  r({id:"thonglor-supanniga", name:"Supanniga Eating Room ทองหล่อ", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"อาหารไทยอีสาน", rating:4.5, reviewCount:1450, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,200",
    address:"160/11 ซ.สุขุมวิท 55", travel:"BTS ทองหล่อ • เดิน 5 นาที", hours:"ทุกวัน 11:30-23:00", groupFriendly:"ดีมาก",
    source:"Tripadvisor", sourceUrl:"https://th.tripadvisor.com/Restaurants-g293916-zfn8308062-Bangkok.html",
    notes:"อาหารอีสานสูตรคุณยาย Michelin Plate", signature:["หมูชะมวง","ส้มตำปลาแห้ง","ขนมจีนน้ำยา"], emoji:"🍚",
    gmapReview:[{author:"Sirin K.",rating:5,text:"หมูชะมวงเด็ดสุด สูตรคุณยายต้นตำรับ"},{author:"Pat L.",rating:4,text:"ห้องส่วนตัวสำหรับกลุ่ม บริการดีมาก"}],
    scores:s(22,20,12,15,14,10)}),
  r({id:"thonglor-pizzaria", name:"Peppina ทองหล่อ", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"พิซซ่าอิตาเลียน", rating:4.4, reviewCount:920, priceRange:"฿฿฿฿", pricePerPerson:"฿600-1,000",
    address:"27/1 ซ.สุขุมวิท 33", travel:"BTS ทองหล่อ • เดิน 7 นาที", hours:"ทุกวัน 11:30-22:30", groupFriendly:"ดี",
    source:"Tripadvisor", sourceUrl:"https://th.tripadvisor.com/Restaurants-g293916-zfn8308062-Bangkok.html",
    notes:"พิซซ่าเตาฟืนแบบ Neapolitan แท้", signature:["Pizza Margherita DOC","Burrata Pizza"], emoji:"🍕",
    gmapReview:[{author:"Tom V.",rating:5,text:"พิซซ่าเตาฟืน แป้งบางกรอบ Burrata พิเศษมาก"},{author:"Bell M.",rating:4,text:"พิซซ่าน่าโพล่งที่สุดในกรุงเทพ"}],
    scores:s(22,17,11,14,14,9)}),
  r({id:"thonglor-yamaguchi", name:"Yamaguchi Wagyu", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"เนื้อย่างญี่ปุ่น", rating:4.5, reviewCount:169, priceRange:"฿฿฿฿฿", pricePerPerson:"฿1,500-3,000",
    address:"ทองหล่อ", travel:"BTS ทองหล่อ • เดิน 5 นาที", hours:"ทุกวัน 17:00-23:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/japanese-restaurants-at-thonglor",
    notes:"Wagyu A5 ราคาจับต้องได้แบบ A La Carte", signature:["Wagyu A5","Yukke","Kobe Beef Tartare"], emoji:"🥩",
    gmapReview:[{author:"Nick L.",rating:5,text:"เนื้อ A5 ในราคาจับต้องได้ ระบบดูดควันเยี่ยม"},{author:"Joe K.",rating:4,text:"ยุกเกะอร่อยมาก เนื้อสด"}],
    scores:s(22,16,8,14,13,10)}),
  r({id:"thonglor-gyoza", name:"Osaka Gyoza Fifty Fifth", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ญี่ปุ่น / เกี๊ยวซ่า", rating:4.1, reviewCount:240, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"Fifty Fifth Thonglor", travel:"BTS ทองหล่อ • เดิน 5 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/japanese-restaurants-at-thonglor",
    notes:"ราชาเกี๊ยวซ่าจากโอซาก้า ปั้นสดทุกชิ้น", signature:["เกี๊ยวซ่าย่าง","Takoyaki","เกี๊ยวซ่านาเบะ"], emoji:"🥟",
    gmapReview:[{author:"Mim L.",rating:4,text:"เกี๊ยวซ่าด้านนอกเหลืองทองกรอบ ด้านในฉ่ำ"},{author:"Pat S.",rating:4,text:"ทาโกะยากิเซต B คุ้มมาก กินกลุ่มอิ่ม"}],
    scores:s(20,16,13,15,12,8)}),
  r({id:"thonglor-mybeefshop", name:"My Beef Shop", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"สเต๊ก / เนื้อย่าง", rating:4.3, reviewCount:550, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,200",
    address:"125/24 ถ.ทองหล่อ", travel:"BTS ทองหล่อ • เดิน 6 นาที", hours:"ทุกวัน 11:30-01:00", groupFriendly:"ดี",
    source:"Grab", sourceUrl:"https://www.grab.com/th/en/food-blog/ร้านอาหารไทยทองหล่อ/",
    notes:"เนื้อย่างเตาฟืน เปิดดึกถึงตี 1", signature:["Tomahawk Steak","Ribeye"], emoji:"🥩",
    gmapReview:[{author:"Aof T.",rating:4,text:"Tomahawk ขนาดใหญ่ จุใจ เหมาะกลุ่มเพื่อน"},{author:"Pun K.",rating:4,text:"เปิดถึงตี 1 ตอบโจทย์มื้อดึก"}],
    scores:s(21,16,11,13,13,9)}),
  r({id:"thonglor-supanusorn", name:"ศุภนุสรณ์ ทองหล่อ", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"อาหารไทยโบราณ", rating:4.6, reviewCount:380, priceRange:"฿฿฿฿", pricePerPerson:"฿650-1,100",
    address:"ทองหล่อ 13", travel:"BTS ทองหล่อ • เดิน 10 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ดี",
    source:"Tripadvisor", sourceUrl:"https://th.tripadvisor.com/Restaurants-g293916-zfn8308062-zfp9-Bangkok.html",
    notes:"อาหารไทยตำรับวังเก่า สูตรโบราณ", signature:["ห่อหมกใบยอ","ม้าฮ่อ","ทอดมันปลา"], emoji:"👑",
    gmapReview:[{author:"Phin K.",rating:5,text:"สูตรโบราณตำรับวัง รสกลมกล่อม ห้องส่วนตัวสวย"},{author:"Tee S.",rating:4,text:"อาหารไทยรสมือคุณยาย กลับมาอีกแน่นอน"}],
    scores:s(22,17,11,11,14,10)}),
  r({id:"thonglor-okumuras", name:"Okumura's Japanese", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ญี่ปุ่น / สุกี้ยากี้", rating:4.3, reviewCount:265, priceRange:"฿฿฿฿฿", pricePerPerson:"฿1,200-2,200",
    address:"ทองหล่อ", travel:"BTS ทองหล่อ • เดิน 6 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/japanese-restaurants-at-thonglor",
    notes:"สุกี้ยากี้คันไซ + ชาบูแบบญี่ปุ่น", signature:["Sukiyaki A4 Wagyu","Kurobuta Pork Set"], emoji:"🍲",
    gmapReview:[{author:"Ging G.",rating:4,text:"สุกี้ยากี้คันไซ Kurobuta Pork นุ่ม"},{author:"Mark P.",rating:4,text:"ระดับพรีเมียม ลายเนื้อสวย มันแทรกดี"}],
    scores:s(21,16,9,14,13,9)}),

  // ============ อโศก (20 ร้าน) ============
  r({id:"asoke-thelocal", name:"The Local by Oamthong", area:"asoke", areaTh:"อโศก", cuisine:"อาหารไทยดั้งเดิม", rating:4.6, reviewCount:1450, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,200",
    address:"32-32/1 ซ.สุขุมวิท 23", travel:"BTS อโศก • เดิน 6 นาที", hours:"ทุกวัน 11:30-23:00", groupFriendly:"ดีมาก",
    source:"Tripadvisor, Time Out", sourceUrl:"https://www.timeout.com/bangkok/restaurants/best-restaurants-and-cafes-asoke",
    notes:"บ้านไทยโบราณ สูตรครอบครัว มีห้องส่วนตัว", signature:["แกงเหลืองสับปะรด","หมูชะมวง","ปลากระเบนผัดฉ่า"], emoji:"🏡",
    gmapReview:[{author:"Sara V.",rating:5,text:"บ้านไทยโบราณสวยมาก สูตรครอบครัวสืบทอด"},{author:"Phin T.",rating:5,text:"แกงเหลืองสับปะรดเด็ดสุด ห้องส่วนตัวสำหรับกลุ่ม"}],
    scores:s(24,20,11,14,15,10)}),
  r({id:"asoke-appia", name:"Appia", area:"asoke", areaTh:"อโศก", cuisine:"อิตาเลียน (Roman)", rating:4.5, reviewCount:580, priceRange:"฿฿฿฿", pricePerPerson:"฿800-1,400",
    address:"20/4 Soi Sukhumvit 31", travel:"BTS อโศก • เดิน 10 นาที", hours:"ทุกวัน 11:30-14:00, 17:00-22:00", groupFriendly:"ดี",
    source:"Thaiger, Tripadvisor", sourceUrl:"https://thethaiger.com/guides/best-of/food/10-best-restaurants-in-asoke-bangkok",
    notes:"Roman trattoria แท้ porchetta จากเตาทุกคืน", signature:["Porchetta","Cacio e Pepe","Chicken Liver Crostini"], emoji:"🍝",
    gmapReview:[{author:"Marco V.",rating:5,text:"Porchetta ตำรับโรมแท้ ๆ ร้านที่ดีที่สุดของกรุงเทพ"},{author:"Ella K.",rating:4,text:"Cacio e Pepe คลาสสิค รสจัดถึงเครื่อง"}],
    scores:s(22,17,11,11,14,10)}),
  r({id:"asoke-bigmama", name:"Big Mama Pizzeria", area:"asoke", areaTh:"อโศก", cuisine:"พิซซ่า / อิตาเลียน", rating:4.3, reviewCount:410, priceRange:"฿฿฿", pricePerPerson:"฿450-700",
    address:"139 ซ.สุขุมวิท 21", travel:"BTS อโศก • เดิน 8 นาที", hours:"ทุกวัน 11:00-23:00", groupFriendly:"ดีมาก",
    source:"Time Out", sourceUrl:"https://www.timeout.com/bangkok/restaurants/best-restaurants-and-cafes-asoke",
    notes:"Trattoria sharable platters พิซซ่าเตาฟืน", signature:["Pizza Margherita","Fettuccine Alfredo","Calamari"], emoji:"🍕",
    gmapReview:[{author:"Andrea P.",rating:5,text:"พิซซ่าเตาฟืน Sharable platters เหมาะกลุ่ม"},{author:"Ploy P.",rating:4,text:"บรรยากาศ trattoria อบอุ่น เครื่องดื่มไวน์ดี"}],
    scores:s(21,19,14,12,14,9)}),
  r({id:"asoke-elgaucho", name:"El Gaucho Steakhouse", area:"asoke", areaTh:"อโศก", cuisine:"สเต๊กอาร์เจนตินา", rating:4.3, reviewCount:193, priceRange:"฿฿฿฿฿", pricePerPerson:"฿1,500-2,500",
    address:"สุขุมวิท ซ.19", travel:"BTS อโศก • เดิน 5 นาที", hours:"ทุกวัน 18:00-23:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/best-of-wongnai-2015-nana-asoke-prompong",
    notes:"สเต๊กระดับพรีเมียม ปิ้งย่างหน้าโต๊ะ", signature:["Argentinian Ribeye","Empanadas","Chimichurri"], emoji:"🥩",
    gmapReview:[{author:"Carlos M.",rating:5,text:"สเต๊กอาร์เจนตินาแท้ ๆ Chimichurri หอม"},{author:"Tee P.",rating:4,text:"ปิ้งย่างหน้าโต๊ะ บรรยากาศคุ้มราคา"}],
    scores:s(20,19,8,14,15,10)}),
  r({id:"asoke-kapraotapae", name:"กะเพราตาแป๊ะ อโศก", area:"asoke", areaTh:"อโศก", cuisine:"อาหารตามสั่ง", rating:4.2, reviewCount:129, priceRange:"฿฿", pricePerPerson:"฿100-200",
    address:"ซ.สุขุมวิท 23", travel:"BTS อโศก • เดิน 5 นาที", hours:"ทุกวัน 10:00-21:00", groupFriendly:"ปานกลาง",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-around-asok",
    notes:"กะเพราเนื้อสับเด็ดดวง ขวัญใจคนทำงาน", signature:["กะเพราเนื้อสับไข่ดาว","ผัดกระเพราหมูกรอบ"], emoji:"🍳",
    gmapReview:[{author:"Riang S.",rating:4,text:"กะเพราเนื้อสับเผ็ดอร่อย ขวัญใจคนอโศก"},{author:"Kong T.",rating:4,text:"ขวดเหล้าน่ารักเก็บได้ ราคาดี"}],
    scores:s(19,12,13,14,13,7)}),
  r({id:"asoke-bankara", name:"Bankara Ramen", area:"asoke", areaTh:"อโศก", cuisine:"ราเมนญี่ปุ่น", rating:4.2, reviewCount:680, priceRange:"฿฿฿", pricePerPerson:"฿350-550",
    address:"Terminal 21 ชั้น G", travel:"BTS อโศก • เดิน 1 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/asoke-lineman-delivery",
    notes:"ราเมนต้นตำรับโตเกียว น้ำซุปเข้มข้น", signature:["Bankara Ramen","Kakuni Pork Belly"], emoji:"🍜",
    gmapReview:[{author:"Lab P.",rating:4,text:"น้ำซุปเข้มข้นกลมกล่อม Kakuni ละลายในปาก"},{author:"Pak C.",rating:4,text:"ติด BTS อโศก สะดวกมาก"}],
    scores:s(21,14,14,15,13,7)}),
  r({id:"asoke-gigi", name:"Gigi Eatery", area:"asoke", areaTh:"อโศก", cuisine:"อิตาเลียน", rating:4.4, reviewCount:340, priceRange:"฿฿฿฿", pricePerPerson:"฿600-1,000",
    address:"Sacha's Hotel Uno, Sukhumvit 19", travel:"BTS อโศก • เดิน 4 นาที", hours:"ทุกวัน 07:00-24:00", groupFriendly:"ดีมาก",
    source:"Time Out", sourceUrl:"https://www.timeout.com/bangkok/restaurants/best-restaurants-and-cafes-asoke",
    notes:"Italian comfort สีสันสนุก มีโซนชั้น 2", signature:["Truffle Arancini","Pappardelle al Ragù","Tiramisu"], emoji:"🍷",
    gmapReview:[{author:"Marco G.",rating:5,text:"Truffle Arancini กรอบเฮือก Pappardelle เด็ดมาก"},{author:"Suzy P.",rating:4,text:"บรรยากาศสีสันสนุก เหมาะนัดกลุ่ม"}],
    scores:s(22,19,12,15,14,9)}),
  r({id:"asoke-spectrum", name:"Spectrum Lounge & Bar", area:"asoke", areaTh:"อโศก", cuisine:"Rooftop / นานาชาติ", rating:4.4, reviewCount:680, priceRange:"฿฿฿฿฿", pricePerPerson:"฿1,200-2,000",
    address:"Hyatt Regency, ซ.สุขุมวิท 13", travel:"BTS นานา/อโศก • เดิน 8 นาที", hours:"ทุกวัน 17:00-01:00", groupFriendly:"ดี",
    source:"Thaiger", sourceUrl:"https://thethaiger.com/guides/best-of/food/10-best-restaurants-in-asoke-bangkok",
    notes:"Rooftop วิวกรุงเทพ + ดนตรีสด + ปิ้งย่าง", signature:["Charcoal-grilled Wagyu","Signature Cocktails"], emoji:"🌃",
    gmapReview:[{author:"Vince L.",rating:5,text:"วิวกรุงเทพสวยมาก ดนตรีสด ค็อกเทลครีเอทีฟ"},{author:"Nina B.",rating:4,text:"ปิ้งย่างชั้น 29 บรรยากาศพิเศษ"}],
    scores:s(22,16,9,12,14,10)}),
  r({id:"asoke-mezze", name:"Mezze", area:"asoke", areaTh:"อโศก", cuisine:"Lebanese / Middle Eastern", rating:4.3, reviewCount:215, priceRange:"฿฿฿", pricePerPerson:"฿450-800",
    address:"3/F, 158-160 ซ.สุขุมวิท 16", travel:"MRT สุขุมวิท • เดิน 7 นาที", hours:"ทุกวัน 11:00-23:00", groupFriendly:"ดี",
    source:"Time Out", sourceUrl:"https://www.timeout.com/bangkok/restaurants/best-restaurants-and-cafes-asoke",
    notes:"Lebanese แท้ ตกแต่งสีฟ้าทะเลกับ Evil Eye", signature:["Skewered Minced Meat","Lemon Chicken","Hummus"], emoji:"🥙",
    gmapReview:[{author:"Omar K.",rating:5,text:"Hummus เด็ด ไก่หมักเลมอนหอมเครื่องเทศ"},{author:"Bee P.",rating:4,text:"บรรยากาศตุรกี อาหารเลบานอนแท้"}],
    scores:s(21,17,13,12,14,10)}),
  r({id:"asoke-pagoda", name:"Pagoda Chinese Restaurant", area:"asoke", areaTh:"อโศก", cuisine:"อาหารจีนกวางตุ้ง", rating:4.5, reviewCount:520, priceRange:"฿฿฿฿฿", pricePerPerson:"฿1,000-1,800",
    address:"Marriott Marquis Queen's Park", travel:"BTS พร้อมพงษ์/อโศก • เดิน 10 นาที", hours:"ทุกวัน 11:30-22:30", groupFriendly:"ดีมาก",
    source:"Culture Trip", sourceUrl:"https://theculturetrip.com/asia/thailand/articles/the-10-best-restaurants-in-sukhumvit-bangkok",
    notes:"กวางตุ้งระดับโรงแรม โต๊ะหมุน เหมาะกลุ่ม", signature:["Peking Duck","Crab Rice","Chili Chicken"], emoji:"🥢",
    gmapReview:[{author:"Chen W.",rating:5,text:"เป็ดปักกิ่งระดับโรงแรม ครอบครัวฟิน"},{author:"Wei L.",rating:4,text:"โต๊ะหมุนได้ เหมาะกลุ่มใหญ่ บริการดี"}],
    scores:s(22,20,9,12,14,10)}),
  r({id:"asoke-longtable", name:"Long Table", area:"asoke", areaTh:"อโศก", cuisine:"ไทยโมเดิร์น", rating:4.2, reviewCount:790, priceRange:"฿฿฿฿฿", pricePerPerson:"฿1,000-1,800",
    address:"25/F, Column Bangkok, ซ.สุขุมวิท 16", travel:"MRT สุขุมวิท • เดิน 6 นาที", hours:"ทุกวัน 17:00-01:00", groupFriendly:"ดีมาก",
    source:"Culture Trip", sourceUrl:"https://theculturetrip.com/asia/thailand/articles/the-10-best-restaurants-in-sukhumvit-bangkok",
    notes:"โต๊ะยาว 25 เมตร วิวกรุงเทพ เหมาะกลุ่ม", signature:["Pomelo Shrimp Salad","Pad Thai","Massaman Curry"], emoji:"🌆",
    gmapReview:[{author:"Anna L.",rating:5,text:"โต๊ะยาวเด็ด วิวกรุงเทพสุดยอด เหมาะกลุ่ม"},{author:"Tim K.",rating:4,text:"Pomelo Shrimp Salad ต้องสั่ง"}],
    scores:s(21,20,9,12,14,10)}),
  r({id:"asoke-saawaan", name:"Saawaan", area:"asoke", areaTh:"อโศก", cuisine:"อาหารไทย Fine Dining", rating:4.7, reviewCount:380, priceRange:"฿฿฿฿฿", pricePerPerson:"฿2,500-4,500",
    address:"39/19 ซ.สุขุมวิท 18", travel:"MRT สุขุมวิท • เดิน 8 นาที", hours:"อ-ส 18:00-23:00", groupFriendly:"ปานกลาง",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-Bangkok.html",
    notes:"Tasting Menu ไทยร่วมสมัย Michelin 1 ดาว", signature:["Yum","Tom","Tam"], emoji:"⭐",
    gmapReview:[{author:"David T.",rating:5,text:"Tasting menu สุดยอด ไทยร่วมสมัย Michelin คุ้ม"},{author:"Pat W.",rating:5,text:"ประสบการณ์ที่ไม่ลืม รายละเอียดทุกจาน"}],
    scores:s(23,13,7,12,14,10)}),
  r({id:"asoke-greyhound-asoke", name:"Greyhound Café Terminal 21", area:"asoke", areaTh:"อโศก", cuisine:"ฟิวชั่นไทย / ฝรั่ง", rating:4.0, reviewCount:680, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"Terminal 21 ชั้น 3", travel:"BTS อโศก • เดิน 1 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/restaurants?regions=225",
    notes:"ฟิวชั่นยอดนิยม คุ้ม-อร่อย ติด BTS", signature:["Spaghetti Drunken Noodle","Crispy Chicken Wing"], emoji:"🐕",
    gmapReview:[{author:"Joe T.",rating:4,text:"Spaghetti ขี้เมาเด็ด ติด BTS สะดวกมาก"},{author:"Ploy M.",rating:4,text:"ฟิวชั่นสไตล์ไทย-ฝรั่ง คนเยอะตลอด"}],
    scores:s(20,17,14,15,13,7)}),
  r({id:"asoke-yasuda", name:"Yasuda Wagyu", area:"asoke", areaTh:"อโศก", cuisine:"เนื้อโกเบ / Wagyu", rating:4.6, reviewCount:185, priceRange:"฿฿฿฿฿", pricePerPerson:"฿2,000-3,500",
    address:"นราธิวาส 7 (ใกล้ MRT)", travel:"MRT สุขุมวิท • เดิน 12 นาที", hours:"ทุกวัน 17:30-23:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/restaurants?regions=225",
    notes:"เนื้อ Kobe ระดับพรีเมียม A5 สุดยอด", signature:["Kobe A5 Ribeye","Beef Tongue"], emoji:"🐄",
    gmapReview:[{author:"Ken L.",rating:5,text:"เนื้อ A5 สวรรค์ของคนรักเนื้อ ลายมันแทรกสวย"},{author:"Anan T.",rating:5,text:"คุณภาพสูงมาก คุ้มกับราคา"}],
    scores:s(22,15,8,10,14,10)}),
  r({id:"asoke-koreatown", name:"Sukhumvit Plaza (Korea Town)", area:"asoke", areaTh:"อโศก", cuisine:"อาหารเกาหลี", rating:4.1, reviewCount:920, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"212-217 ซ.สุขุมวิท 12", travel:"BTS อโศก • เดิน 5 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Time Out", sourceUrl:"https://www.timeout.com/bangkok/restaurants/best-restaurants-and-cafes-asoke",
    notes:"คอมมูนิตี้เกาหลี รวมร้านอาหารเกาหลี 10+", signature:["Korean BBQ","Bibimbap","Tteokbokki"], emoji:"🇰🇷",
    gmapReview:[{author:"Yun P.",rating:4,text:"คอมมูนิตี้เกาหลี ร้านเยอะ ราคาประหยัด"},{author:"Eun M.",rating:4,text:"เลือกร้านเกาหลีได้ทุกประเภทใน 1 ที่"}],
    scores:s(20,16,14,15,13,8)}),
  r({id:"asoke-mercy", name:"Mercy Republic", area:"asoke", areaTh:"อโศก", cuisine:"นานาชาติ", rating:4.4, reviewCount:340, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"Sukhumvit ใกล้ MRT", travel:"BTS อโศก • เดิน 6 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/RestaurantsNear-g293916-d2539704-Asoke_Residence_Sukhumvit_by_UHG-Bangkok.html",
    notes:"นานาชาติ pad thai - burger - tiramisu ครบ", signature:["Pad Thai","Veggie Burger","Tiramisu"], emoji:"🌍",
    gmapReview:[{author:"Helen R.",rating:5,text:"We Love Mercy Republic อาหารหลากหลาย ครบ"},{author:"Ben K.",rating:4,text:"Tiramisu อย่าพลาด พนักงานเป็นกันเอง"}],
    scores:s(21,17,13,13,13,9)}),
  r({id:"asoke-avra", name:"Avra Greek Restaurant", area:"asoke", areaTh:"อโศก", cuisine:"อาหารกรีก", rating:4.5, reviewCount:280, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,200",
    address:"สุขุมวิท ซ.31", travel:"BTS อโศก • เดิน 10 นาที", hours:"ทุกวัน 11:30-23:00", groupFriendly:"ดี",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-Bangkok.html",
    notes:"อาหารกรีกแท้ มี plate smashing", signature:["Saganaki","Lamb","Greek Salad"], emoji:"🇬🇷",
    gmapReview:[{author:"George K.",rating:5,text:"Saganaki ชีสไฟลุก Lamb อร่อยมาก"},{author:"Marina T.",rating:5,text:"Plate smashing สนุก บรรยากาศกรีกแท้"}],
    scores:s(22,17,11,11,14,10)}),
  r({id:"asoke-ministry", name:"Ministry of Crab", area:"asoke", areaTh:"อโศก", cuisine:"ปู / ซีฟู้ด", rating:4.4, reviewCount:520, priceRange:"฿฿฿฿฿", pricePerPerson:"฿1,500-2,800",
    address:"ใกล้ BTS อโศก", travel:"BTS อโศก • เดิน 5 นาที", hours:"ทุกวัน 11:30-23:00", groupFriendly:"ดี",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-zfp58-Bangkok.html",
    notes:"ปูยักษ์จากศรีลังกา ซิกเนเจอร์ Chili Crab", signature:["Chili Crab","Pepper Crab","Crab Rice"], emoji:"🦀",
    gmapReview:[{author:"James T.",rating:5,text:"Humongous crab! Chili crab เด็ดมาก"},{author:"Lisa W.",rating:4,text:"คุ้มราคา ปูตัวใหญ่จริง"}],
    scores:s(22,17,8,15,14,10)}),
  r({id:"asoke-indus", name:"Indus Indian Restaurant", area:"asoke", areaTh:"อโศก", cuisine:"อินเดีย", rating:4.5, reviewCount:480, priceRange:"฿฿฿", pricePerPerson:"฿500-900",
    address:"สุขุมวิท ซ.26", travel:"BTS พร้อมพงษ์/อโศก • เดิน 8 นาที", hours:"ทุกวัน 11:30-23:00", groupFriendly:"ดี",
    source:"Culture Trip", sourceUrl:"https://theculturetrip.com/asia/thailand/articles/the-10-best-restaurants-in-sukhumvit-bangkok",
    notes:"อาหารอินเดียทั้งคาวมังสวิรัติ", signature:["Butter Chicken","Galouti Kebab","Naan"], emoji:"🍛",
    gmapReview:[{author:"Raj P.",rating:5,text:"Amazing Indian Food! Galouti kebab สุดยอด"},{author:"Priya M.",rating:5,text:"Tasting menu คุ้มมาก ทั้งคาวและมัง"}],
    scores:s(22,16,12,13,14,9)}),

  // ============ พร้อมพงษ์ (20 ร้าน) ============
  r({id:"phromphong-lukkaithong", name:"ลูกไก่ทอง EmQuartier", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"อาหารไทย", rating:4.3, reviewCount:1204, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"EmQuartier ชั้น 7", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/emquartier-department-store-restaurants",
    notes:"อาหารไทยต้นตำรับ ราดหน้าและแกงป่าลือชื่อ", signature:["ราดหน้าเนื้อ","แกงป่า","ปังชา"], emoji:"🍛",
    gmapReview:[{author:"Art K.",rating:4,text:"ราดหน้าเนื้อเข้มข้น แกงป่าเผ็ดร้อน ปังชาต้องสั่ง"},{author:"Sa L.",rating:4,text:"ติด BTS พร้อมพงษ์ สะดวกมาก"}],
    scores:s(22,19,13,15,14,8)}),
  r({id:"phromphong-fourseasons", name:"Four Seasons Chinese EmQuartier", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"อาหารจีน / ติ่มซำ", rating:4.1, reviewCount:294, priceRange:"฿฿฿฿", pricePerPerson:"฿600-1,000",
    address:"EmQuartier ชั้น 7", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/emquartier-department-store-restaurants",
    notes:"ติ่มซำคุณภาพดี โต๊ะใหญ่หมุนสำหรับกลุ่ม", signature:["ฮะเก๋ากุ้ง","เป็ดปักกิ่ง","ขาหมูตุ๋น"], emoji:"🥟",
    gmapReview:[{author:"Wei C.",rating:4,text:"ติ่มซำคุณภาพ เป็ดปักกิ่งหนังกรอบ"},{author:"Ming K.",rating:4,text:"โต๊ะหมุน เหมาะกลุ่มครอบครัว/ทีม"}],
    scores:s(20,20,12,15,14,9)}),
  r({id:"phromphong-audrey", name:"Audrey Cafe des Fleurs", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"ฟิวชั่น / ไทย", rating:3.9, reviewCount:167, priceRange:"฿฿฿฿", pricePerPerson:"฿500-900",
    address:"EmQuartier ชั้น 8", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/emquartier-department-store-restaurants",
    notes:"ตกแต่งสวย ดอกไม้เต็มร้าน", signature:["พิซซ่าต้มยำกุ้ง","ก๋วยเตี๋ยวต้มยำ"], emoji:"🌸",
    gmapReview:[{author:"Bell S.",rating:4,text:"ดอกไม้เต็มร้าน ถ่ายรูปสวย พิซซ่าต้มยำเด็ด"},{author:"Mim P.",rating:3,text:"บรรยากาศดี ราคาสูงเมื่อเทียบ"}],
    scores:s(18,16,12,15,14,9)}),
  r({id:"phromphong-arnos", name:"Arno's Steak EmQuartier", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"สเต๊ก / เบอร์เกอร์", rating:4.0, reviewCount:685, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,100",
    address:"EmQuartier ชั้น G", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 11:00-23:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/emquartier-department-store-restaurants",
    notes:"สเต๊กเนื้อโคขุนเกรดพรีเมียม", signature:["Ribeye Steak","Truffle Burger"], emoji:"🥩",
    gmapReview:[{author:"Tar K.",rating:4,text:"Ribeye เนื้อนุ่ม Truffle Burger หอม"},{author:"Joe P.",rating:4,text:"สเต๊กราคาคุ้ม คุณภาพในห้าง"}],
    scores:s(20,16,11,15,14,8)}),
  r({id:"phromphong-thongsmith-em", name:"ทองสมิทธ์ EmQuartier", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"ก๋วยเตี๋ยวเรือ", rating:4.6, reviewCount:870, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"EmQuartier ชั้น 7", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดี",
    source:"Trip.com, Wongnai", sourceUrl:"https://th.trip.com/moments/theme/poi-emquartier-30656212-restaurant-993134/",
    notes:"ก๋วยเตี๋ยวเรือสาขาใหม่ วิวมุมสูง", signature:["ก๋วยเตี๋ยวเรือเนื้อ","ก๋วยเตี๋ยววากิว"], emoji:"🍜",
    gmapReview:[{author:"Gigi S.",rating:5,text:"นั่งใกล้กระจกเห็นวิวกรุงเทพสวย วากิวนุ่ม"},{author:"Pim K.",rating:4,text:"ก๋วยเตี๋ยวเรือเข้มข้น ราคาคุ้ม"}],
    scores:s(23,16,14,15,14,9)}),
  r({id:"phromphong-mozza", name:"Mozza by Cocotte", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"อิตาเลียน Homemade", rating:4.2, reviewCount:412, priceRange:"฿฿฿฿", pricePerPerson:"฿650-1,100",
    address:"EmQuartier ชั้น G", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"BKKMenu", sourceUrl:"https://www.bkkmenu.com/eat/stories/helix-sky-dining-at-emquartier.html",
    notes:"อิตาเลียนสูตรคุณย่า บรรยากาศ cozy", signature:["Burrata Salad","Tagliatelle Bolognese","Tiramisu"], emoji:"🧀",
    gmapReview:[{author:"Marco N.",rating:4,text:"Burrata สดมาก Tagliatelle Bolognese คลาสสิค"},{author:"Pat S.",rating:4,text:"บรรยากาศ cozy เหมาะนัดดินเนอร์คู่"}],
    scores:s(21,17,12,15,14,9)}),
  r({id:"phromphong-emsphere", name:"EmSphere Food Hall", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"ฟู้ดคอร์ทนานาชาติ", rating:4.2, reviewCount:850, priceRange:"฿฿฿", pricePerPerson:"฿250-500",
    address:"EmSphere ชั้น 5", travel:"BTS พร้อมพงษ์ • เดิน 2 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/restaurants?regions=225",
    notes:"ฟู้ดคอร์ทใหม่ล่าสุด รวมร้านชื่อดัง 50+", signature:["หลากหลายตัวเลือก","ห้องส่วนตัวจองได้"], emoji:"🍱",
    gmapReview:[{author:"Pin K.",rating:4,text:"รวมร้านเด็ดในที่เดียว เลือกทานสะดวก"},{author:"Mod P.",rating:5,text:"นั่งสบาย กลุ่มใหญ่นั่งได้ทุกแบบ"}],
    scores:s(20,20,15,15,13,8)}),
  r({id:"phromphong-zaapeli", name:"Zaab Eli (แซ่บอีลี่)", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"อาหารอีสาน", rating:3.9, reviewCount:96, priceRange:"฿฿฿", pricePerPerson:"฿300-500",
    address:"EmQuartier", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/emquartier-department-store-restaurants",
    notes:"อีสานสไตล์ครีเอทีฟใน EmQuartier", signature:["ส้มตำกุ้งสด","คอหมูย่าง","ลาบ"], emoji:"🥬",
    gmapReview:[{author:"Mai T.",rating:4,text:"อีสานในห้าง ตำกุ้งสดเด็ด"},{author:"Joe N.",rating:4,text:"รสชาติแซ่บ พื้นที่กว้าง โต๊ะใหญ่นั่งได้"}],
    scores:s(18,17,13,15,12,8)}),
  r({id:"phromphong-bolan", name:"Bo.lan", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"อาหารไทย Fine Dining", rating:4.6, reviewCount:420, priceRange:"฿฿฿฿฿", pricePerPerson:"฿2,500-4,000",
    address:"24 ซ.สุขุมวิท 53", travel:"BTS ทองหล่อ/พร้อมพงษ์ • เดิน 10 นาที", hours:"พ-อา 18:00-22:30", groupFriendly:"ปานกลาง",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-Bangkok.html",
    notes:"Thai Fine Dining สูตรโบราณ ใช้วัตถุดิบ Local", signature:["Tasting Menu","Curry","Spicy Salad"], emoji:"🌿",
    gmapReview:[{author:"Anna B.",rating:5,text:"ไทย Fine Dining สูตรโบราณ ทุกจานมีเรื่องราว"},{author:"David L.",rating:5,text:"Tasting menu คุ้มประสบการณ์"}],
    scores:s(23,12,7,12,14,10)}),
  r({id:"phromphong-suhring", name:"Sühring", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"อาหารเยอรมัน Fine Dining", rating:4.7, reviewCount:380, priceRange:"฿฿฿฿฿", pricePerPerson:"฿3,500-5,500",
    address:"10 Yen Akat ซ.3", travel:"BTS พร้อมพงษ์ • เดิน 15 นาที", hours:"จ-ส 18:00-23:00", groupFriendly:"ปานกลาง",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-Bangkok.html",
    notes:"เยอรมัน Fine Dining 2 Michelin Stars", signature:["Tasting Menu","Schweinshaxe Modern","Pretzels"], emoji:"🌟",
    gmapReview:[{author:"Klaus M.",rating:5,text:"2 Michelin Stars สมราคาทุกบาท"},{author:"Sara K.",rating:5,text:"German cuisine นำเสนอแบบโมเดิร์น"}],
    scores:s(23,10,7,9,14,10)}),
  r({id:"phromphong-coca", name:"Coca Suki", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"สุกี้ / ไทย-จีน", rating:4.1, reviewCount:580, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"EmQuartier ชั้น G", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/places/emquartier",
    notes:"สุกี้เก่าแก่ของไทย คนต่อคิวยาวเหยียด", signature:["สุกี้น้ำ","สุกี้แห้ง","ติ่มซำ"], emoji:"🍲",
    gmapReview:[{author:"Wat T.",rating:4,text:"สุกี้ดังของไทย รสคลาสสิค กลุ่มใหญ่นั่งได้"},{author:"Boo K.",rating:4,text:"น้ำจิ้มสุกี้สูตรลับ ติดใจ"}],
    scores:s(20,20,14,15,13,8)}),
  r({id:"phromphong-isao", name:"Isao", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"ฟิวชั่นญี่ปุ่น", rating:4.3, reviewCount:670, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,200",
    address:"5 ซ.สุขุมวิท 31", travel:"BTS พร้อมพงษ์/อโศก • เดิน 8 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ดี",
    source:"Culture Trip", sourceUrl:"https://theculturetrip.com/asia/thailand/articles/the-10-best-restaurants-in-sukhumvit-bangkok",
    notes:"ซูชิฟิวชั่นกึ่งกลางอโศก-พร้อมพงษ์", signature:["Chicago Spicy Crazy Roll","Rainbow Roll"], emoji:"🍣",
    gmapReview:[{author:"Brad K.",rating:5,text:"Signature rolls สนุก หลากชื่อ Chicago Spicy เด็ด"},{author:"Sun P.",rating:4,text:"ฟิวชั่นญี่ปุ่นสร้างสรรค์ ราคาคุ้ม"}],
    scores:s(22,17,11,12,14,10)}),
  r({id:"phromphong-bei-otto", name:"Bei Otto", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"อาหารเยอรมัน", rating:4.3, reviewCount:520, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,200",
    address:"1 ซ.สุขุมวิท 20", travel:"BTS พร้อมพงษ์ • เดิน 6 นาที", hours:"ทุกวัน 11:00-23:00", groupFriendly:"ดีมาก",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-Bangkok.html",
    notes:"เบียร์เยอรมันสด อาหารเยอรมันแท้", signature:["Schweinshaxe","Bratwurst","Sauerkraut"], emoji:"🍺",
    gmapReview:[{author:"Otto K.",rating:5,text:"Schweinshaxe ดีงาม เบียร์เยอรมันสดทุกแก้ว"},{author:"Mia T.",rating:4,text:"บรรยากาศ Bavarian Beer Garden เหมาะกลุ่ม"}],
    scores:s(21,19,11,14,14,9)}),
  r({id:"phromphong-greyhound-em", name:"Greyhound Café EmQuartier", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"ฟิวชั่นไทย", rating:3.9, reviewCount:240, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"EmQuartier ชั้น 2", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/emquartier-department-store-restaurants",
    notes:"ฟิวชั่นไทยสไตล์โมเดิร์น แบรนด์ดังในไทย", signature:["Pad Kee Mao Spaghetti","Crispy Chicken"], emoji:"🐕",
    gmapReview:[{author:"Aim P.",rating:4,text:"พาสต้าผัดขี้เมาเด็ด Greyhound คลาสสิค"},{author:"Run K.",rating:4,text:"ฟิวชั่นไทยน่ารัก ติด BTS"}],
    scores:s(19,17,14,15,13,7)}),
  r({id:"phromphong-bunker", name:"Bunker Bangkok", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"นานาชาติ / Fine Dining", rating:4.4, reviewCount:285, priceRange:"฿฿฿฿฿", pricePerPerson:"฿2,000-3,500",
    address:"118/2 ซ.สาทร 12", travel:"BTS พร้อมพงษ์ • เดิน 15 นาที", hours:"จ-ส 18:00-23:00", groupFriendly:"ปานกลาง",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-Bangkok.html",
    notes:"Modern American/European โดยเชฟดัง", signature:["Wagyu Tartare","Lobster"], emoji:"🍴",
    gmapReview:[{author:"Tom P.",rating:5,text:"Modern fine dining ครีเอทีฟทุกจาน"},{author:"Anne M.",rating:4,text:"Wagyu tartare สุดยอด ราคาสมเหตุสมผล"}],
    scores:s(22,13,7,10,14,10)}),
  r({id:"phromphong-kuppa", name:"Kuppa Café", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"คาเฟ่ / brunch", rating:4.2, reviewCount:710, priceRange:"฿฿฿", pricePerPerson:"฿350-600",
    address:"39 ซ.สุขุมวิท 16", travel:"MRT สุขุมวิท • เดิน 8 นาที", hours:"ทุกวัน 09:30-22:00", groupFriendly:"ดี",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-Bangkok.html",
    notes:"คาเฟ่บรันช์โบราณ ขวัญใจชาวสุขุมวิท", signature:["Eggs Benedict","Pasta","Apple Pie"], emoji:"☕",
    gmapReview:[{author:"Sara T.",rating:4,text:"คาเฟ่ขวัญใจชาวสุขุมวิท Eggs Benedict ที่นี่ดี"},{author:"Pim P.",rating:4,text:"Apple Pie ต้นตำรับ ครบเครื่อง"}],
    scores:s(21,16,13,13,13,8)}),
  r({id:"phromphong-medici", name:"Medici Kitchen Sirocco", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"อิตาเลียน", rating:4.4, reviewCount:340, priceRange:"฿฿฿฿฿", pricePerPerson:"฿1,500-2,800",
    address:"Hotel Muse, สุขุมวิท Soi 39", travel:"BTS พร้อมพงษ์ • เดิน 8 นาที", hours:"ทุกวัน 18:00-23:00", groupFriendly:"ดี",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-Bangkok.html",
    notes:"อิตาเลียนระดับโรงแรม Hotel Muse", signature:["Risotto Truffle","Wagyu Grilled","Tiramisu"], emoji:"🍝",
    gmapReview:[{author:"Carlo M.",rating:5,text:"Risotto Truffle, Wagyu Grilled อร่อยมาก หัวใจฟิน"},{author:"Bum K.",rating:5,text:"บริการดีจาก Khun Bum, Aoi, Aon"}],
    scores:s(22,17,9,13,14,10)}),
  r({id:"phromphong-fillets", name:"Fillets Sukhumvit 39", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"สเต๊ก / นานาชาติ", rating:4.5, reviewCount:225, priceRange:"฿฿฿฿", pricePerPerson:"฿800-1,400",
    address:"สุขุมวิท ซ.39", travel:"BTS พร้อมพงษ์ • เดิน 7 นาที", hours:"ทุกวัน 11:30-23:00", groupFriendly:"ดี",
    source:"Tripadvisor", sourceUrl:"https://www.tripadvisor.com/Restaurants-g293916-zfn15620328-Bangkok.html",
    notes:"สเต๊กพรีเมียมคุณภาพดี บริการเป็นกันเอง", signature:["Fillet Mignon","Ribeye","Steak Frites"], emoji:"🥩",
    gmapReview:[{author:"Pete S.",rating:5,text:"Fillet Mignon นุ่มมาก บริการอบอุ่น"},{author:"Min K.",rating:5,text:"Bum, Kae, Bo, Kae ให้บริการดีเยี่ยม"}],
    scores:s(22,15,10,13,14,10)}),
  r({id:"phromphong-tewn", name:"Tewn Tewn Phrom Phong", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"ไทยร่วมสมัย", rating:4.0, reviewCount:185, priceRange:"฿฿฿", pricePerPerson:"฿400-700",
    address:"EmQuartier ชั้น 8", travel:"BTS พร้อมพงษ์ • เดิน 1 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Trip.com", sourceUrl:"https://th.trip.com/moments/theme/poi-emquartier-30656212-restaurant-993134/",
    notes:"อาหารไทยร่วมสมัย แชร์กันได้", signature:["ห่อหมกฟิวชั่น","ผัดสะตอกุ้ง","น้ำพริกอ่อง"], emoji:"🌶️",
    gmapReview:[{author:"Aim K.",rating:4,text:"ไทยร่วมสมัย sharing dishes สนุก"},{author:"Beam L.",rating:4,text:"ห่อหมกฟิวชั่นรสดี เหมาะดินเนอร์"}],
    scores:s(19,17,13,15,12,8)}),

  // ============ เพิ่มร้าน ชาบู / ปิ้งย่าง / บุฟเฟ่ต์ ครอบคลุมทุกย่าน ============
  r({id:"siam-momoparadise", name:"Mo-Mo-Paradise สยามสแควร์วัน", area:"siam", areaTh:"สยาม", cuisine:"บุฟเฟ่ต์ชาบู / สุกี้ยากี้", rating:4.2, reviewCount:480, priceRange:"฿฿฿฿", pricePerPerson:"฿599-899",
    address:"Siam Square One ชั้น 5", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/places/siam-square-one",
    notes:"ชาบูบุฟเฟ่ต์ต้นตำรับจากญี่ปุ่น น้ำซุป 3 รส", signature:["ชาบูชาบู","สุกี้ยากี้","คารามิโสะ"], emoji:"🍲",
    gmapReview:[{author:"Mind P.",rating:4,text:"บุฟเฟ่ต์ชาบูต้นตำรับ น้ำซุปคารามิโสะเด็ด"},{author:"Pat T.",rating:4,text:"เนื้อคุณภาพดี เครื่องเคียงครบ กลุ่มใหญ่นั่งสบาย"}],
    scores:s(21,20,12,15,13,8)}),
  r({id:"siam-bonchon", name:"Bonchon Korean Chicken สยาม", area:"siam", areaTh:"สยาม", cuisine:"ไก่ทอดเกาหลี / นั่งทาน", rating:4.0, reviewCount:580, priceRange:"฿฿฿", pricePerPerson:"฿300-500",
    address:"Siam Square One ชั้น 4", travel:"BTS สยาม • เดิน 3 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/places/siam-square-one",
    notes:"ไก่ทอดเกาหลีกรอบนอกนุ่มใน ซอสคลาสสิคและซอสกระเทียม", signature:["Soy Garlic Wings","Spicy Drumsticks"], emoji:"🍗",
    gmapReview:[{author:"Aim B.",rating:4,text:"ไก่ทอดเกาหลีกรอบมาก ซอสเด็ด เหมาะแชร์กลุ่ม"},{author:"Mod P.",rating:4,text:"เสิร์ฟไว ราคาคุ้ม"}],
    scores:s(20,16,13,15,13,7)}),
  r({id:"ari-akiyoshi", name:"Akiyoshi Buffet อารีย์", area:"ari", areaTh:"อารีย์", cuisine:"บุฟเฟ่ต์ปิ้งย่าง / ญี่ปุ่น", rating:4.1, reviewCount:520, priceRange:"฿฿฿฿", pricePerPerson:"฿599-1,099",
    address:"La Villa Ari ชั้น 2", travel:"BTS อารีย์ • เดิน 5 นาที", hours:"ทุกวัน 11:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/recommended-restaurants-at-aree",
    notes:"บุฟเฟ่ต์ปิ้งย่างสไตล์ญี่ปุ่น เนื้อหลายเกรด", signature:["Wagyu Set","Pork Belly","Premium Seafood"], emoji:"🥩",
    gmapReview:[{author:"Yui K.",rating:4,text:"บุฟเฟ่ต์ปิ้งย่างคุ้มราคา เนื้อหมักหอม"},{author:"Tar S.",rating:4,text:"นั่งกลุ่มกินสนุก น้ำจิ้มหลายแบบ"}],
    scores:s(20,20,12,14,13,8)}),
  r({id:"ari-kiryu", name:"Kiryu Shabu อารีย์", area:"ari", areaTh:"อารีย์", cuisine:"ชาบูพรีเมียม / ญี่ปุ่น", rating:4.4, reviewCount:340, priceRange:"฿฿฿฿", pricePerPerson:"฿800-1,400",
    address:"ใกล้ BTS อารีย์", travel:"BTS อารีย์ • เดิน 6 นาที", hours:"ทุกวัน 11:30-22:00", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/recommended-restaurants-at-aree",
    notes:"ชาบูพรีเมียม น้ำซุปเข้มข้น เนื้อ Wagyu A4-A5", signature:["Wagyu Shabu","ซุปต้มยำกุ้ง","Truffle Shabu"], emoji:"🍲",
    gmapReview:[{author:"Pim N.",rating:5,text:"ชาบูพรีเมียม เนื้อนุ่ม น้ำซุปเข้มข้น"},{author:"Bee L.",rating:4,text:"บรรยากาศโมเดิร์น สะอาด เหมาะนัดดินเนอร์"}],
    scores:s(22,18,11,12,13,9)}),
  r({id:"thonglor-marusu", name:"Marusu Yakiniku ทองหล่อ", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"ปิ้งย่างญี่ปุ่น / Wagyu", rating:4.5, reviewCount:780, priceRange:"฿฿฿฿", pricePerPerson:"฿800-1,500",
    address:"ทองหล่อ ใกล้ BTS", travel:"BTS ทองหล่อ • เดิน 5 นาที", hours:"ทุกวัน 17:00-23:30", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/japanese-restaurants-at-thonglor",
    notes:"ยากินิคุญี่ปุ่นแท้ มีห้องส่วนตัวสำหรับกลุ่ม", signature:["A5 Wagyu Set","Beef Tongue","Yukke"], emoji:"🥩",
    gmapReview:[{author:"Ken T.",rating:5,text:"ยากินิคุญี่ปุ่นแท้ มีห้องส่วนตัวกลุ่ม 10 คน"},{author:"Aof P.",rating:4,text:"เนื้อ A5 มันแทรกสวย ระบบดูดควันเยี่ยม"}],
    scores:s(22,20,10,15,14,10)}),
  r({id:"thonglor-akakara", name:"Akakara Shabu Buffet", area:"thonglor", areaTh:"ทองหล่อ", cuisine:"บุฟเฟ่ต์ชาบูญี่ปุ่น", rating:4.2, reviewCount:625, priceRange:"฿฿฿฿", pricePerPerson:"฿599-999",
    address:"ทองหล่อ ซ.10", travel:"BTS ทองหล่อ • เดิน 8 นาที", hours:"ทุกวัน 11:00-23:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-in-thonglor",
    notes:"ชาบูบุฟเฟ่ต์ญี่ปุ่น น้ำซุปอาคาคาระระดับเผ็ดเลือกได้", signature:["Aka Spicy Soup","Tonkotsu Soup","Premium Beef"], emoji:"🍲",
    gmapReview:[{author:"Min P.",rating:4,text:"บุฟเฟ่ต์ชาบูเผ็ดระดับ 1-9 เลือกได้ ฟินมาก"},{author:"Joe T.",rating:4,text:"เนื้อเยอะ ผักครบ คุ้มราคามาก"}],
    scores:s(20,20,12,13,13,8)}),
  r({id:"asoke-akiyoshi", name:"Akiyoshi Buffet อโศก", area:"asoke", areaTh:"อโศก", cuisine:"บุฟเฟ่ต์ชาบู / ปิ้งย่าง", rating:4.0, reviewCount:920, priceRange:"฿฿฿", pricePerPerson:"฿499-799",
    address:"Sukhumvit Plaza ซ.12", travel:"BTS อโศก • เดิน 5 นาที", hours:"ทุกวัน 11:00-22:30", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-around-asok",
    notes:"บุฟเฟ่ต์ชาบู+ปิ้งย่างในที่เดียว เนื้อหลายชนิด", signature:["Beef Set","Premium Seafood","Salmon"], emoji:"🍱",
    gmapReview:[{author:"Mac K.",rating:4,text:"ชาบูปิ้งย่างในที่เดียว เนื้อเยอะ คุ้มราคา"},{author:"Boo P.",rating:4,text:"พื้นที่กว้าง รับกลุ่มใหญ่ได้สบาย"}],
    scores:s(20,20,14,15,13,7)}),
  r({id:"asoke-sukishi", name:"Sukishi Korean Charcoal Grill", area:"asoke", areaTh:"อโศก", cuisine:"บุฟเฟ่ต์ปิ้งย่างเกาหลี", rating:4.1, reviewCount:550, priceRange:"฿฿฿", pricePerPerson:"฿499-899",
    address:"Terminal 21 ชั้น 5", travel:"BTS อโศก • เดิน 1 นาที", hours:"ทุกวัน 10:00-22:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/restaurants-around-asok",
    notes:"บุฟเฟ่ต์ปิ้งย่างเกาหลี+ชาบู สาขาในห้าง", signature:["Korean BBQ Beef","Bulgogi","Kimchi Stew"], emoji:"🇰🇷",
    gmapReview:[{author:"Mam K.",rating:4,text:"บุฟเฟ่ต์ปิ้งย่างเกาหลี ติด BTS สะดวก"},{author:"Bell N.",rating:4,text:"เครื่องเคียงเกาหลีครบ น้ำจิ้มดี"}],
    scores:s(20,20,13,15,13,7)}),
  r({id:"phromphong-penguin", name:"Penguin Eat Shabu", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"บุฟเฟ่ต์ชาบู / สุกี้", rating:4.3, reviewCount:1100, priceRange:"฿฿฿", pricePerPerson:"฿399-699",
    address:"EmQuartier ใกล้ทางเชื่อม BTS", travel:"BTS พร้อมพงษ์ • เดิน 3 นาที", hours:"ทุกวัน 11:00-23:00", groupFriendly:"ดีมาก",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/places/emquartier",
    notes:"บุฟเฟ่ต์ชาบูสไตล์เพนกวิน น้ำซุปหลายรส", signature:["น้ำซุปทงคัตสึ","หม่าล่า","Bingsu"], emoji:"🐧",
    gmapReview:[{author:"Pae W.",rating:4,text:"บุฟเฟ่ต์ชาบูราคาเป็นมิตร น้ำซุปหลายรส"},{author:"Mai R.",rating:5,text:"Bingsu ของหวานฟรี เด็กชอบ กลุ่มใหญ่นั่งได้"}],
    scores:s(22,20,15,15,13,8)}),
  r({id:"phromphong-buffetgyumon", name:"Gyu-Mon Yakiniku", area:"phromphong", areaTh:"พร้อมพงษ์", cuisine:"ปิ้งย่างญี่ปุ่น / Wagyu", rating:4.3, reviewCount:680, priceRange:"฿฿฿฿", pricePerPerson:"฿700-1,200",
    address:"Emporium Tower ชั้น 6", travel:"BTS พร้อมพงษ์ • เดิน 3 นาที", hours:"ทุกวัน 11:30-22:30", groupFriendly:"ดี",
    source:"Wongnai", sourceUrl:"https://www.wongnai.com/listings/emquartier-department-store-restaurants",
    notes:"ยากินิคุญี่ปุ่น เนื้อหลายเกรดให้เลือก", signature:["Wagyu Karubi","Premium Tongue","Beef Steak"], emoji:"🥩",
    gmapReview:[{author:"Nik K.",rating:4,text:"เนื้อย่างคุณภาพดี ราคาคุ้มเทียบกับห้าง"},{author:"Bee N.",rating:4,text:"บริการดี เหมาะดินเนอร์กับเพื่อน"}],
    scores:s(21,17,11,15,13,9)})
];

// Top ranked
window.TOP_RANKED = [...window.RESTAURANTS].sort((a, b) => b.scores.total - a.scores.total);

// Data sources
window.DATA_SOURCES = [
  { name: "Wongnai", url: "https://www.wongnai.com", logo: "🍴", desc: "รีวิว/Rating/ราคา/รูปจากผู้ใช้จริง > 100 ร้าน" },
  { name: "Google Maps", url: "https://maps.google.com", logo: "📍", desc: "ตำแหน่ง, รีวิว, เวลาทำการ" },
  { name: "Tripadvisor", url: "https://www.tripadvisor.com", logo: "🦉", desc: "Filter \"Large groups\" ตามย่าน" },
  { name: "Grab Food Blog", url: "https://www.grab.com/th/en/food-blog/", logo: "🛵", desc: "Grab rating + รีวิว + ราคาแบบ $$$$" },
  { name: "Time Out Bangkok", url: "https://www.timeout.com/bangkok", logo: "🗞️", desc: "บทวิจารณ์เชิงลึกของ critic" },
  { name: "Ryoii Review", url: "https://www.ryoiireview.com", logo: "📝", desc: "Curated lists ของแต่ละย่าน" }
];

// Tools
window.TOOLS = [
  { name: "Apify", icon: "🤖", role: "Web scraping ร้านอาหารจาก Google Maps + Wongnai (100 ร้าน)", category: "Data Collection" },
  { name: "Google Sheets", icon: "📊", role: "เก็บ Raw + Clean data, Scoring table", category: "Data Storage" },
  { name: "Claude AI", icon: "✨", role: "Clean data, normalize ราคา/cuisine, scoring, insight", category: "AI Analysis" },
  { name: "n8n", icon: "⚙️", role: "Automation: trigger สรุปข้อมูลและส่ง Slack daily", category: "Automation" },
  { name: "HTML / CSS / JS", icon: "🎨", role: "Final output รายงานแบบ interactive", category: "Final Output" },
  { name: "Vercel", icon: "🚀", role: "Deploy หน้าเว็บออนไลน์", category: "Deployment" }
];

// Workflow
window.WORKFLOW = [
  { step: 1, title: "Problem Framing", desc: "ตั้งโจทย์: หาร้านสำหรับทีม 8-12 คน, 5 ย่าน, เกณฑ์เลือก", icon: "🎯" },
  { step: 2, title: "Data Collection", desc: "Scrape ร้าน 100 จาก Google Maps + Wongnai ด้วย Apify", icon: "🔍" },
  { step: 3, title: "Data Storage", desc: "Import เข้า Google Sheets แยก Raw / Clean", icon: "📥" },
  { step: 4, title: "Data Cleaning", desc: "Claude ช่วย normalize ราคา / รวมร้านซ้ำ / fill missing fields", icon: "🧹" },
  { step: 5, title: "Scoring", desc: "ให้คะแนน 100 คะแนนตาม 6 หมวด (น้ำหนักตามโจทย์)", icon: "⭐" },
  { step: 6, title: "AI Analysis", desc: "Claude หา insight, trade-off, Top 3 พร้อมเหตุผล", icon: "🤖" },
  { step: 7, title: "Automation", desc: "n8n workflow แจ้ง Slack เมื่อมีร้านใหม่/rating เปลี่ยน", icon: "🔁" },
  { step: 8, title: "HTML Output", desc: "หน้าเว็บ interactive รายงานผลทั้งหมด", icon: "🎁" }
];

// ============================================
// บทวิเคราะห์ AI (อบไว้ถาวร — ใช้บน Vercel ได้เลยโดยไม่ต้องเรียก AI สด)
// key = id ของร้าน · ภาษาเป็นกันเอง อ่านง่ายเหมือนเพื่อนแนะนำ
// ============================================
window.AI_ANALYSIS = {
  "phromphong-onktse": {
    analysis: "ร้านบุฟเฟต์อาหารทะเลที่คนรีวิวเยอะมากและคะแนนสูงสุดในกลุ่ม ถ้าทีมชอบกินกุ้งหอยปูปลาแบบไม่อั้น ที่นี่ตอบโจทย์สุด อยู่แถวพร้อมพงษ์เดินทางสะดวก แค่ควรโทรจองโต๊ะใหญ่ล่วงหน้าหน่อย",
    pros: ["บุฟเฟต์ทะเลกินได้ไม่อั้น คุ้มราคา", "คนรีวิวเยอะ การันตีว่าอร่อยจริง"],
    cons: ["โต๊ะกลุ่มใหญ่ควรจองล่วงหน้า"]
  },
  "siam-8qfjea": {
    analysis: "ร้านชาบูแบบหม้อเดี่ยว ใครชอบกินของใครของมันไม่ต้องแย่งกันจะถูกใจมาก อยู่กลางสยามเดินทางง่าย เหมาะกับทีมที่อยากกินสบายๆ ไม่วุ่นวาย แต่ช่วงคนเยอะอาจต้องรอคิวบ้าง",
    pros: ["หม้อเดี่ยวของใครของมัน ไม่ต้องแย่ง", "อยู่กลางสยาม เดินทางสะดวก"],
    cons: ["ช่วงคนเยอะอาจต้องรอคิว"]
  },
  "siam-19m8xns": {
    analysis: "บุฟเฟต์ที่คนชอบกันเยอะ คะแนนดี เลือกกินได้หลากหลายตามใจ เหมาะกับทีมที่แต่ละคนชอบกินไม่เหมือนกัน อยู่ในสยามหาง่าย ราคากลางๆ กำลังดี",
    pros: ["บุฟเฟต์เลือกได้หลากหลาย ถูกใจทุกคน", "อยู่ในสยาม หาง่าย"],
    cons: ["ช่วงวันหยุดคนเยอะ ควรเผื่อเวลา"]
  }
};
